### ISSUE TITLE
Could we add Quad9 servers?

### ISSUE THREAD

**Issue by m0urs** [DNSCrypt/dnscrypt-resolvers#1]
Could we please add the Quad9 servers: https://www.quad9.net
IPv4: 9.9.9.9 and 142.112.112.112
IPv6: 2620:fe::fe

Although not officially documented yet, the servers are TLS enabled: https://labs.ripe.net/Members/stephane_bortzmeyer/quad9-a-public-dns-resolver-with-security

Thanks,
Michael

**Comment by publicarray** [comment]
Sorry, but DNS-over-TLS is a different protocol than DNSCrypt so this will not work.

**Comment by m0urs** [comment]
Ah, sorry. Yes, I just learned that these are two different things. Thank you!
