### ISSUE TITLE
rubyfish.cn server change ip

### ISSUE THREAD

**Issue by qyb** [DNSCrypt/dnscrypt-resolvers#103]
ea-dns.rubyfish.cn
sdns://AgUAAAAAAAAAAAASZWEtZG5zLnJ1YnlmaXNoLmNuCi9kbnMtcXVlcnk

uw-dns.rubyfish.cn
sdns://AgUAAAAAAAAAAAASdXctZG5zLnJ1YnlmaXNoLmNuCi9kbnMtcXVlcnk

**Comment by jedisct1** [comment]
Updated, thanks!
