### ISSUE TITLE
new securedns.eu adblocking dns servers

### ISSUE THREAD

**Issue by kzshantonu** [DNSCrypt/dnscrypt-resolvers#106]
Please add the new DNS with ad-blocking: https://securedns.eu/#ads

Keep up the good work, btw
Thanks

**Comment by pengelana** [comment]
Stamp for securedns-ipv6-doh is incorrect.

`sdns://AgcAAAAAAAAAGjJhMDM6YjBjMDowOjEwMTA6OmU5YTozMDAxABBkb2guc2VjdXJlZG5zLmV1Ci9kbnMtcXVlcnk`

`[2019-05-01 06:42:33] [ERROR] Get https://doh.securedns.eu/dns-query?ct=&dns=yv4BAAABAAAAAAABAAACAAEAACkQAAAAgAAAAA: dial tcp: address 2a03:b0c0:0:1010::e9a:3001:443: too many colons in address`

New Stamp:

`sdns://AgcAAAAAAAAAHFsyYTAzOmIwYzA6MDoxMDEwOjplOWE6MzAwMV0AEGRvaC5zZWN1cmVkbnMuZXUKL2Rucy1xdWVyeQ`

**Comment by pengelana** [comment]
#120 PR submitted
