### ISSUE TITLE
Obtaining server properties

### ISSUE THREAD

**Issue by Magalame** [DNSCrypt/dnscrypt-resolvers#117]
Hi!

I'm trying to go through the list of public solvers, in order to measure which is fastest. The old CSV format was good for that since we could just read off the ip, and whether the server would log, etc.  
How would one do that with the stamps? 

Thanks!

**Comment by jedisct1** [comment]
dnscrypt-proxy already finds the fastest servers, once at the beginning, and then dynamically, constantly trying to see if another server would be a better candidate than the current ones.

The latency of each server is printed when the service starts.

You can also use filters to select only servers with specific properties (protocol, no log, ipv6, etc).

If you want to reimplement this yourself, you can parse the [DNS stamps](https://dnscrypt.info/stamps-specifications), or use the existing code in [Go](https://github.com/jedisct1/go-dnsstamps), Rust and [Javascript](https://github.com/jedisct1/vue-dnsstamp).

Or way easier, run `dnscrypt-proxy -list -json` or `dnscrypt-proxy -list-all -json`. You will get a nice JSON object as a result, with all the servers properties, always up-to-date, and matching the filters you need.

This is how it currently looks like (without filters):

https://gist.github.com/6dfce86510201fd9cd6240e22f68a1c5

Measuring DNS latency is tricky. You can't just use `ping`. Some servers can have a low ping, but then they are very slow at actually returning DNS records, especially non-cached ones.

For DoH servers, ping doesn't make any sense, especially for those using CDNs. You need to measure the latency after the TLS handshake, as (re)connections are slow, but then a couple round trips can use that connection before having to reconnect.
