### ISSUE TITLE
public-resolvers returning invalid signature

### ISSUE THREAD

**Issue by sirn** [DNSCrypt/dnscrypt-resolvers#121]
Current fetching a new public-resolvers.md is currently returning:

```
[2019-05-01 18:18:26] [CRITICAL] Unable to use source [public-resolvers]: [Invalid signature]
[2019-05-01 18:18:26] [FATAL] No servers configured
```

I think this is because @jedisct1 forgot to sign the latest commit (c13404d403e8752fed9754a3a1695651df8a9db9)?

**Comment by jedisct1** [comment]
Sorry for that. It's now signed.

**Comment by sirn** [comment]
Thanks for maintaining the list!
