### ISSUE TITLE
"cisco" server responds with OpenDNS (Cisco Umbrella) account filtering rules applied, if it was setup and configured for client's IP address

### ISSUE THREAD

**Issue by konstantinngvk1** [DNSCrypt/dnscrypt-resolvers#122]
If OpenDNS account was configured and client IP address was setup in OpenDNS account (statically or via DDNS from client side), then "cisco" resolver (208.67.220.220) answers on DNS queries with OpenDNS (Cisco Umbrella) account DNS filtering rules applied. 

Below is an example of request. 146.112.61.106 receved as youtube.com's address is an 'block' address within OpenDNS block of addresses (as shown by whois) for such an account received via 'cisco' resolver with dnscrypt-proxy on Ubuntu 18.04 LTS server. Also, an untrusted HTTPS certificate for youtube.com signed by "Cisco Umbrella Secondary SubCA ams-SG" received.

Seems that this behavior should be fixed with Cisco, or listed in 'cisco' resolver description.

![изображение](https://user-images.githubusercontent.com/35524273/57178426-6fa92e00-6e78-11e9-8733-1af0a5cc574b.png)

root@bgw01:/usr/share/dnscrypt-proxy# dig youtube.com
; <<>> DiG 9.10.3-P4-Ubuntu <<>> youtube.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 60886
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;youtube.com.                   IN      A

;; ANSWER SECTION:
youtube.com.            0       IN      A       146.112.61.106

root@bgw01:/usr/share/dnscrypt-proxy# whois 146.112.61.106
...
Found a referral to whois.ripe.net.

% This is the RIPE Database query service.
% The objects are in RPSL format.
%
% The RIPE Database is subject to Terms and Conditions.
% See http://www.ripe.net/db/support/db-terms-conditions.pdf

% Note: this output has been filtered.
%       To receive output for a database update, use the "-B" flag.

% Information related to '146.112.0.0 - 146.112.255.255'

% No abuse contact registered for 146.112.0.0 - 146.112.255.255

inetnum:        146.112.0.0 - 146.112.255.255
netname:        OpenDNS-RIPE
descr:          OpenDNS
country:        US
admin-c:        ODNS36692-RIPE
tech-c:         ODNS36692-RIPE
status:         LEGACY
mnt-by:         OPENDNS-MNT
mnt-routes:     OPENDNS-MNT
mnt-domains:    OPENDNS-MNT
mnt-by:         OPENDNS-MNT
mnt-lower:      OPENDNS-MNT
created:        1970-01-01T00:00:00Z
last-modified:  2019-04-08T07:51:51Z
source:         RIPE

role:           OPENDNS NETENG TEAM
address:        OpenDNS
address:        675 West Hastings Street, Suite 500
address:        Vancouver BC V6B 1N2
address:        Canada
phone:          +1 415 513 0439
abuse-mailbox:  abuse@opendns.com
nic-hdl:        ODNS36692-RIPE
mnt-by:         OPENDNS-MNT
created:        2014-05-29T13:22:57Z
last-modified:  2015-01-22T18:28:03Z
source:         RIPE # Filtered

% This query was served by the RIPE Database Query Service version 1.93.2 (WAGYU)

**Comment by jedisct1** [comment]
So, you configured something, and what happens matches what you configured. That sounds... like the expected behavior?

The "no filter" flag is not set for these resolvers, as they have been reported to redirect browsers to their servers even when nothing was configured. You're supposed to install and ultimately trust an custom root certificate to "get rid of the warning". This allows them to silently decrypt and tamper with your HTTPS traffic, so I wouldn't recommend it.

To avoid servers returning intentionally wrong results, keep `require_nofilter` set to `false`.

**Comment by konstantinngvk1** [comment]
Unexpected and not matched what I've configured. 

OpenDNS declared another set of DNS servers - 208.67.222.222, 208.67.220.220. Never ever mentioned that "cisco" resolver is a part of "OpenDNS" filtering service.  No single word about it neither in dnscrypt-resolvers.csv neither in servers ilist at dnscrypt.info. 

I configured OpenDNS for testing on separate host in my network behind NAT, but OpenDNS settings affected dnscrypt resolver.

**Comment by jedisct1** [comment]
The OpenDNS company doesn't exist any more. It was acquired by Cisco in 2015 for $635 million dollars. https://techcrunch.com/2015/06/30/cisco-to-buy-cloud-security-company-opendns-for-635m-in-cash/

**Comment by konstantinngvk1** [comment]
I do not ever used words "OpenDNS Company". I used "OpenDNS Service" instead. 

This well known fact changes nothing with that 'filtered' and 'OpenDNS affected' nature should be listed at dnscrypt related materials about this resolver.
