### ISSUE TITLE
okturtles

### ISSUE THREAD

**Issue by horus1963** [DNSCrypt/dnscrypt-resolvers#13]
Is it possible to add okturtles to your resolver list?

## okturtles
For a surveillance-free world. HTTPS is broken. DNSChain fixes it.
sdns://AQIAAAAAAAAAETIzLjIyNi4yMjcuOTM6NDQzIB2FOVPjT6_QBflMb9HM5jXUEZkEDUjRml01C2p8gXPLHTIuZG5zY3J5cHQtY2VydC5va3R1cnRsZXMuY29t

**Comment by jedisct1** [comment]
Does it work again? The maintainer asked for it to be removed.

**Comment by horus1963** [comment]
You are absolutely correct. It does not work! I should have checked before contacting you. I was misled by the fact that it was on Mastad0n's US list.

Thanks a lot for a great software and the excellent support.

**Comment by jedisct1** [comment]
Hope it will be back soon!
