### ISSUE TITLE
zeroaim-ipv6 will be offline soon

### ISSUE THREAD

**Issue by zzzkeil** [DNSCrypt/dnscrypt-resolvers#131]
Hi,
i move to a new server, in the next few days / weeks.

Removing the following server from the list is necessary.
It´s my ipv6 server : 

> zeroaim-ipv6
> dnscrypt-server Docker image : DNSSEC/Non-logged/Uncensored Hosted in Germany
> sdns://AQcAAAAAAAAAGVsyYTAzOjQwMDA6YjoyMjM6OjFdOjg0NDMgcrQcuGXx2fhX6rmtaP6aPXj8gumVIrn4GIrn6aTB1fUfMi5kbnNjcnlwdC1jZXJ0Lnplcm9haW0uZGUtaXB2Ng

A new dnscrypt server from me, will come back in August/September

Thanks

**Comment by jedisct1** [comment]
Thanks for the heads up!

It has been removed.
