### ISSUE TITLE
Google may have changed their certificate

### ISSUE THREAD

**Issue by jaydeethree** [DNSCrypt/dnscrypt-resolvers#132]
DoH to Google isn't working due to a certificate issue:

dnscrypt-proxy[8808]: System DNS configuration not usable yet, exceptionally resolving [dns.google.com] using fallback resolver [8.8.8.8:53]
dnscrypt-proxy[8808]: Certificate hash [1ef624cfff5e6bd3baddf3fddbfdea565467e377299dc7ee6675166f300cc1b9] not found for [google]

I'm assuming this means that Google updated their certificate - can it please be updated in the public-resolvers list as well?

Thanks so much!

**Comment by jedisct1** [comment]
Google's certificates don't seem to have changed here.

Can you run the proxy with:

```sh
env SHOW_CERTS=1 ./dnscrypt-proxy -loglevel 0
```

And report what certificates you get for Google?

**Comment by jaydeethree** [comment]
Here's what I'm seeing - let me know if you need anything else. Thanks!

`dnscrypt-proxy[9815]: [google] TLS version: 304 - Protocol: h2 - Cipher suite: 4867
dnscrypt-proxy[9815]: Advertised cert: [CN=dns.google,O=Google LLC,L=Mountain View,ST=California,C=US] [33099122fe1ae43b4d16ac03b3a210a10b045af7ea22eea933526f362ae98903]
dnscrypt-proxy[9815]: Advertised cert: [CN=GTS CA 1O1,O=Google Trust Services,C=US] [76802447a019931a3f004304c53fdc6c1b2c378dc4be8f73b39fd9c969dfb445]
dnscrypt-proxy[9815]: Certificate hash [1ef624cfff5e6bd3baddf3fddbfdea565467e377299dc7ee6675166f300cc1b9] not found for [google]
dnscrypt-proxy[9815]: dnscrypt-proxy is waiting for at least one server to be reachable
dnscrypt-proxy[9815]: [google] TLS version: 304 - Protocol: h2 - Cipher suite: 4867
dnscrypt-proxy[9815]: Advertised cert: [CN=dns.google,O=Google LLC,L=Mountain View,ST=California,C=US] [33099122fe1ae43b4d16ac03b3a210a10b045af7ea22eea933526f362ae98903]
dnscrypt-proxy[9815]: Advertised cert: [CN=GTS CA 1O1,O=Google Trust Services,C=US] [76802447a019931a3f004304c53fdc6c1b2c378dc4be8f73b39fd9c969dfb445]
dnscrypt-proxy[9815]: [google] TLS version: 304 - Protocol: h2 - Cipher suite: 4867
dnscrypt-proxy[9815]: Advertised cert: [CN=dns.google,O=Google LLC,L=Mountain View,ST=California,C=US] [33099122fe1ae43b4d16ac03b3a210a10b045af7ea22eea933526f362ae98903]
dnscrypt-proxy[9815]: Advertised cert: [CN=GTS CA 1O1,O=Google Trust Services,C=US] [76802447a019931a3f004304c53fdc6c1b2c378dc4be8f73b39fd9c969dfb445]
dnscrypt-proxy[9815]: Stopped.`

**Comment by jedisct1** [comment]
I get a different parent certificate (CN=Google Internet Authority G3), but things might be different in your region.

The certificate you reported has been added. Thanks a lot!

**Comment by jaydeethree** [comment]
I can confirm that it's now working again. Thanks so much!
