### ISSUE TITLE
Avoiding downtime on public resolver migration

### ISSUE THREAD

**Issue by EnKrypt** [DNSCrypt/dnscrypt-resolvers#133]
Hey, I have a resolver running that is part of the public resolver list.

I plan to perform a migration to a different host (I've opened an issue in the docker repository whether I can somehow salvage the existing certs and keep the same fingerprint)

But in case, the certs need to be regenerated, and I need a new stamp, what is the best way to ensure that there is minimum downtime for my resolver as I make this transition?

**Comment by jedisct1** [comment]
Hi,

The certs don't need to change as they are not tied to IP addresses, but to the name (e.g. `2.dnscrypt-cert.example.com`).

The best way to avoid downtime would be to set up the new resolver, have the public list updated with the new stamp, wait 3 days for everybody to catch up, and the old resolver can be turned off.

**Comment by EnKrypt** [comment]
So that means I can spin up the same image as a container, with the same certs and keys?

Only the stamp will change as a result of this if I am correct?

**Comment by jedisct1** [comment]
Yes, exactly.
