### ISSUE TITLE
Add new DNSCrypt v2 German server

### ISSUE THREAD

**Issue by jamesponddotco** [DNSCrypt/dnscrypt-resolvers#140]
Hi 👋🏼,

Can you add our new server to the list, please?

Server is hosted with Hetzner in Nuremberg, Germany, has full disk-encryption, Canonical Livepatch for less downtime and full monitoring using a combination of [Uptime Robot](https://uptimerobot.com), [Monit](https://mmonit.com/monit/) and [Statping](https://github.com/hunterlong/statping). It uses the [oficial Docker image](https://github.com/DNSCrypt/dnscrypt-server-docker).

```
[static]
  [static.'dnscrypt-01.adsnomore.io']
  stamp = 'sdns://AQcAAAAAAAAAETk0LjEzMC4xNzguNTY6NDQzIIxpj-7XPoT_79rA9pnvVGz0bIQRuEL-eI-0NlYJaGcpJjIuZG5zY3J5cHQtY2VydC5kbnNjcnlwdC0wMS5tYWRwb255Lmlv'
```

Name is `dnscrypt-01.adsnomore.io`, as more servers will be coming as soon as we finish talking with a few providers in Iceland and Panama.

Thank you! :)

**Comment by jedisct1** [comment]
Hi James!

Welcome to `dnscrypt-01.adsnomore.io` and thank you for running that resolver!

Looks like it works perfectly.

It has been added to the list!

Thanks again!

**Comment by jamesponddotco** [comment]
Thanks for letting us in! :)
