### ISSUE TITLE
Human Filterable Public Resolver List

### ISSUE THREAD

**Issue by snorkasaurus** [DNSCrypt/dnscrypt-resolvers#15]
I have seen issue #4 and the [stamp calculator](https://dnscrypt.info/stamps), as well as the [text based list](https://download.dnscrypt.info/dnscrypt-resolvers/v2/public-resolvers.md) of public resolvers.  However I couldn't find an easy way to find suitable resolvers from the list.  For example, if I wanted to find all servers in Canada that support DNSSEC, do not log, and do not censor, is there any easy way to generate such a list?

The [list at dnscrypt.info](https://dnscrypt.info/public-servers) does allow for sorting but not filtering, and does not include location as a sortable or filterable field.

**Comment by jedisct1** [comment]
Having a map in addition to the list would be fantastic.

If we want to put that on dnscrypt.info, there are quite a few [map components for Vue](https://github.com/vuejs/awesome-vue#map) that all look great.

I can whip up an API that takes a set of IPs and returns their location using GeoIP.

Do you want to work on the map itself?

**Comment by snorkasaurus** [comment]
I wouldn't know where to begin with the mapping, but would be happy with just country info and simple filtering.  Even an unstamped list would help with making an educated decision about server selection.

**Comment by jedisct1** [comment]
https://dnscrypt.info/map/

**Comment by snorkasaurus** [comment]
Would it be possible to have a non-stamped list?  The stamp essentially hides important information that people could [or perhaps should] use to make educated decisions about which resolvers to use.

The map is pretty... but does not provide much information, hides multiple servers in a single location (I think), and in some cases appears to be just plain incorrect.
