### ISSUE TITLE
New DNSCrypt v2 servers

### ISSUE THREAD

**Issue by jamesponddotco** [DNSCrypt/dnscrypt-resolvers#150]
Hi 👋🏼,

Can you add our new servers to the list, please?

Servers have full disk-encryption, Canonical Livepatch enabled and monitoring using a combination of [Uptime Robot](https://uptimerobot.com), [Monit](https://mmonit.com/monit/) and [Statping](https://github.com/hunterlong/statping). All of them use the [oficial Docker image](https://github.com/DNSCrypt/dnscrypt-server-docker).

We would also like to change the description of the `dnscrypt-01.adsnomore.io` server already on the list, as I think it looks too big right now?

**From:**

```
DNSCrypt server hosted with Hetzner in Nuremberg, Germany. No logging, DNSSEC. It has full disk encryption, Canonical Livepatch for less downtime and full monitoring using a combination of Uptime Robot, Monit and Statping. Uses the official Docker image. Operated by @jamesponddotco
```

**To:**

```
DNSCrypt server located in Nuremberg, Germany. No logging, DNSSEC, disk encryption, Canonical Livepatch and monitored 24/7. Uses the official Docker image.
```

## Description and stamps for each new server

```
[static]
  [static.'dnscrypt-02.adsnomore.io']
  stamp = 'sdns://AQcAAAAAAAAAETE0MC44Mi4yNi4xMDM6NDQzIE15px_otxEaCZ20DybtbfMu92IH3Ritg83ibv6LeizTKTIuZG5zY3J5cHQtY2VydC5kbnNjcnlwdC0wMi5tYWRwb255LnNwYWNl'
```

DNSCrypt server located in Miami, USA. No logging, DNSSEC, disk encryption, Canonical Livepatch and monitored 24/7. Uses the official Docker image.

```
[static]
  [static.'dnscrypt-03.adsnomore.io']
  stamp = 'sdns://AQcAAAAAAAAAEDUuMTg4LjIzOC42ODo0NDMg1uv1UTjfRdCF1XDI3T10v4EXWcdK6x8qM5Qut7bwb_gpMi5kbnNjcnlwdC1jZXJ0LmRuc2NyeXB0LTAzLm1hZHBvbnkuc3BhY2U'
```

DNSCrypt server located in São Paulo, Brazil. No logging, DNSSEC, disk encryption, Canonical Livepatch and monitored 24/7. Uses the official Docker image.

```
[static]
  [static.'dnscrypt-04.adsnomore.io']
  stamp = 'sdns://AQcAAAAAAAAAEDQ1LjMyLjMxLjIzMTo0NDMgmk18Se_bsOdRNFJ64Lrw5MJ83y_au6WNrh3lZOceiqgpMi5kbnNjcnlwdC1jZXJ0LmRuc2NyeXB0LTA0Lm1hZHBvbnkuc3BhY2U'
```

DNSCrypt server located in Tokyo, Japan. No logging, DNSSEC, disk encryption, Canonical Livepatch and monitored 24/7. Uses the official Docker image.

```
[static]
  [static.'dnscrypt-05.adsnomore.io']
  stamp = 'sdns://AQcAAAAAAAAAETE0OS4yOC4xNjguNjI6NDQzIENfI6UCxKdNccBA9YW-OhkV-HB_b_Yj5nQbq-gM1TAMKTIuZG5zY3J5cHQtY2VydC5kbnNjcnlwdC0wNS5tYWRwb255LnNwYWNl'
```

DNSCrypt server located in Sydney, Australia. No logging, DNSSEC, disk encryption, Canonical Livepatch and monitored 24/7. Uses the official Docker image.

```
[static]
  [static.'dnscrypt-06.adsnomore.io']
  stamp = 'sdns://AQcAAAAAAAAAEjk1LjE3OS4xNzguMTAwOjQ0MyCzDTlSDfD9-UOciubW46-f6tsh8o60Rt1m4i7XH5hBqykyLmRuc2NyeXB0LWNlcnQuZG5zY3J5cHQtMDYubWFkcG9ueS5zcGFjZQ'
```

DNSCrypt server located in Amsterdam, Netherlands. No logging, DNSSEC, disk encryption, Canonical Livepatch and monitored 24/7. Uses the official Docker image.

```
[static]
  [static.'dnscrypt-07.adsnomore.io']
  stamp = 'sdns://AQcAAAAAAAAAEjEzOS4xODAuMjE2LjgzOjQ0MyBPxDlEgU5vJPp0n-Zh505hgFMSBQj8CQc7p9uUaIWigSkyLmRuc2NyeXB0LWNlcnQuZG5zY3J5cHQtMDcubWFkcG9ueS5zcGFjZQ'
```

DNSCrypt server located in Singapore. No logging, DNSSEC, disk encryption, Canonical Livepatch and monitored 24/7. Uses the official Docker image.

—————

I hope to have a few more to share in a few days.

Thank you! :)

**Comment by jedisct1** [comment]
Wow, that's quite a few new resolvers!

Thanks a lot for running these!

They all have been added.

Thanks!

**Comment by jamesponddotco** [comment]
Thanks for getting them added to the list! 🎉
