### ISSUE TITLE
The relays.md needs its signature been updated.

### ISSUE THREAD

**Issue by IceCodeNew** [DNSCrypt/dnscrypt-resolvers#173]
```
[CRITICAL] Unable to retrieve source [relays]: [Invalid signature]
```

The content of relays.md had been changed 15 hours ago, but its signature was not updated simultaneously. Thus all the DNSCrypt-proxy clients installed on my device(Unfortuanately they were updated, which means they will try to fetch relay.md file in there starting process) refuse to start as they could not validate the relay.md file.

Wish the signature process would be automatically so we could prevent such a nasty thing happens again.

**Comment by IceCodeNew** [comment]
Better discuss this problem here: [#810](https://github.com/DNSCrypt/dnscrypt-proxy/issues/810)

**Comment by jedisct1** [comment]
The next version will be more robust to this: https://github.com/DNSCrypt/dnscrypt-proxy/pull/989
