### ISSUE TITLE
servers marked as nonfiltering started to filter

### ISSUE THREAD

**Issue by Thermi** [DNSCrypt/dnscrypt-resolvers#183]
Found so far:
sfw.scaleway-fr
dnswarden-dc1-ipv6

**Comment by jedisct1** [comment]
Ah, my bad the `sfw.scaleway-fr`. The purpose of that one is to filter explicit content (https://fr.dnscrypt.info/sfw.html), so of course, the nofilter bit should not be set. It was set by accident when the server software was changed.

Do you have example domains that are blocked by `dnswarden-dc1-ipv6`? There are `ads-*` versionos of the `dnswarden` servers blocking ads, but other ones should not filter anything.

**Comment by Thermi** [comment]
You could try resolving thumbs.pr0gramm.com or img.pr0gramm.com.
Or generally any high profile NSFW website.

**Comment by jedisct1** [comment]
`thumbs.pr0gramm.com` doesn't seem to exist. I can't resolve it even using Google or Cloudflare.

**Comment by jedisct1** [comment]
And `img.pr0gramm.com` resolves fine with `dnswarden-dc1-ipv6`.

**Comment by jedisct1** [comment]
NSFW websites being blocked by `sfw` is expected, since this is the whole purpose of that resolver :)

**Comment by Thermi** [comment]
Sorry, the DNS name was "thumb.pr0gramm.com". Well, regarding if a DNS resolver should do something that corresponds with its name (sfw.x resolves only sfw websites): That makes sense. It didn't make sense that it was chosen when my config specified no filtering. 

I explicitely disabled the two DNS resolvers in the configuration file and will report any others that I find.

**Comment by jedisct1** [comment]
Thanks!
