### ISSUE TITLE
Human Filterable Public Resolver List

### ISSUE THREAD

**Issue by snorkasaurus** [DNSCrypt/dnscrypt-resolvers#19]
Seems that issue #15 has been closed and as a peon I am unable to reopen it.

Would it be possible to have a non-stamped list? The stamp essentially hides important information that people could [or perhaps **should**] use to make educated decisions about which resolvers to use.

The map is pretty... but does not provide much information, hides multiple servers in a single location (I think), and in some cases appears to be just plain incorrect.

**Comment by jedisct1** [comment]
`dnscrypt-proxy -list-all -json` should have the extra things you need.

**Comment by snorkasaurus** [comment]
I feel sorry for users who just wish to select which resolvers they connect to. :-(
