### ISSUE TITLE
What happened to dnscrypt.org and the dnscrypt repo?

### ISSUE THREAD

**Issue by mastad0n** [DNSCrypt/dnscrypt-resolvers#2]
Just wondering, sorry if this is the wrong place to ask.

No more dnscrypt?

**Comment by meeeo** [comment]
Same question, when I try to run dnscrypt-update-resolvers.sh , it says  can't find download.dnscrypt.org and when I  open the browser the website becomes dnsprivacy.org , what happend?

**Comment by mazesy** [comment]
> This project was taken offline by its creator and maintainer Frank Denis on the 6th December 2018, after announcing in November 2017 that the project needs a new maintainer.

as published on https://github.com/dyne/dnscrypt-proxy

**Comment by mastad0n** [comment]
@mazesy @meeeo check it out V2:


https://github.com/jedisct1/dnscrypt-proxy

**Comment by mazesy** [comment]
@mastad0n , thanks. V2 acknowledged. Needs work (alpha) but will be a giant DNSCrypt leap.
