### ISSUE TITLE
2 Servers for the Public List

### ISSUE THREAD

**Issue by zzzkeil** [DNSCrypt/dnscrypt-resolvers#20]
I run 2 Servers with your Docker Image,  the last 24 Hours without Problems right now.
The are running on a different Port ( 8443 ).
One Server is on IPv4 , the other on IPv6.
Hosted in Germany

```
   [static.'2.dnscrypt-cert.trashvpn.de']
   stamp = 'sdns://AQcAAAAAAAAAEzM3LjIyMS4xOTUuMTgxOjg0NDMgeWFZIMbyef83QDyIdD3cE9Fe_4QcTDw4nKWJDSacGvYbMi5kbnNjcnlwdC1jZXJ0LnRyYXNodnBuLmRl'

   [static.'2.dnscrypt-cert.zeroaim.de-ipv6']
   stamp = 'sdns://AQcAAAAAAAAAGVsyYTAzOjQwMDA6YjoyMjM6OjFdOjg0NDMgcrQcuGXx2fhX6rmtaP6aPXj8gumVIrn4GIrn6aTB1fUfMi5kbnNjcnlwdC1jZXJ0Lnplcm9haW0uZGUtaXB2Ng'
```

**Comment by jedisct1** [comment]
Great!

How would you like them to be named? `trashvpn` and `zeroaim`?

What nice little description would you like to see in the list between the name and the stamp?

**Comment by zzzkeil** [comment]
maybe like this : 

## trashvpn
Docker Image : DNSSEC/Non-logged/Uncensored
Hosted in Germany
sdns://AQcAAAAAAAAAEzM3LjIyMS4xOTUuMTgxOjg0NDMgeWFZIMbyef83QDyIdD3cE9Fe_4QcTDw4nKWJDSacGvYbMi5kbnNjcnlwdC1jZXJ0LnRyYXNodnBuLmRl

## zeroaim-ipv6
Docker Image : DNSSEC/Non-logged/Uncensored
Hosted in Germany
sdns://AQcAAAAAAAAAGVsyYTAzOjQwMDA6YjoyMjM6OjFdOjg0NDMgcrQcuGXx2fhX6rmtaP6aPXj8gumVIrn4GIrn6aTB1fUfMi5kbnNjcnlwdC1jZXJ0Lnplcm9haW0uZGUtaXB2Ng
