### ISSUE TITLE
Update Needed

### ISSUE THREAD

**Issue by jbaker6953** [DNSCrypt/dnscrypt-resolvers#203]
This list appears to be missing the following OpenNIC resolvers:

ns8.ca.dns.opennic.glue
ns16.de.dns.opennic.glue
ns6.mx.dns.opennic.glue
ns7.nh.nl.dns.opennic.glue
ns12.nh.nl.dns.opennic.glue

The list contains the following resolvers that are no longer listed by OpenNIC:

doh-ibksturm
ibksturm
publicarray-au
publicarray-au-doh
publicarray-au2
publicarray-au2-doh

And the list contains outdated info for the following resolvers:

ethservices
ethservices2

**Comment by jedisct1** [comment]
Can you submit a pull request here? https://github.com/DNSCrypt/dnscrypt-resolvers

Thank you!

**Comment by ibksturm** [comment]
> The list contains the following resolvers that are no longer listed by OpenNIC:
> 
> doh-ibksturm
> ibksturm

Hi @jbaker6953 

Thanks for Feedback, i'm the dude who's running ibksturm and doh-ibksturm

why do you think OPENNIC doesn't run on it. I tested in on my system and it should go

![grafik](https://user-images.githubusercontent.com/35167101/71325169-431a5300-24e9-11ea-94dc-80ec1afbf907.png)

![grafik](https://user-images.githubusercontent.com/35167101/71325171-4f9eab80-24e9-11ea-9a37-bcdaa499ae21.png)
![grafik](https://user-images.githubusercontent.com/35167101/71325177-5e855e00-24e9-11ea-85ba-94da62d64651.png)


so i can't reproduce what's wrong, please help me

@jedisct1 Frank, please reopen

**Comment by jbaker6953** [comment]
Not that it doesn't run, but that it's not listed by OpenNIC: https://servers.opennicproject.org/

**Comment by jbaker6953** [comment]
The other problem I'm having in constructing a pull request is that OpenNIC only provides partial information for some servers. For example, the server ns8.ca.dns.opennic.glue reports "DoH Provided at https://doh.boothlabs.me." There's no information to confirm that the DoH server is using OpenNIC, whether it's logging, whether it has DNSSEC, or anything else.

**Comment by jedisct1** [comment]
None of the missing OpenNIC servers seem to be working.

**Comment by jbaker6953** [comment]
Some work for me:
`[2019-12-22 09:44:54] [NOTICE] [ibksturm] TIMEOUT
[2019-12-22 09:44:59] [NOTICE] [opennic-ethservices2] TIMEOUT
[2019-12-22 09:45:09] [NOTICE] [publicarray-au2] TIMEOUT
[2019-12-22 09:45:09] [NOTICE] [publicarray-au] OK (DNSCrypt) - rtt: 454ms
`

**Comment by ibksturm** [comment]
> Some work for me:
> 
> ```
> [2019-12-22 09:44:54] [NOTICE] [ibksturm] TIMEOUT
> [2019-12-22 09:44:59] [NOTICE] [opennic-ethservices2] TIMEOUT
> [2019-12-22 09:45:09] [NOTICE] [publicarray-au2] TIMEOUT
> [2019-12-22 09:45:09] [NOTICE] [publicarray-au] OK (DNSCrypt) - rtt: 454ms
> ```

![grafik](https://user-images.githubusercontent.com/35167101/71325579-0cdfd200-24ef-11ea-8102-a573727d56a0.png)


interesting..... did you deleted the *.md* file and redownloaded it?

and ya, that's true, i never subscribted my server on opennic public servers

**Comment by jedisct1** [comment]
`ibksturm` works fine for me as well..

```text
[2019-12-22 19:20:15] [NOTICE] [ibksturm] OK (DNSCrypt) - rtt: 48ms
```

**Comment by jedisct1** [comment]
`publicarray-au2` is fine, too:

```text
[2019-12-22 19:21:09] [NOTICE] [publicarray-au2] OK (DNSCrypt) - rtt: 280ms
```

**Comment by jedisct1** [comment]
```text
[2019-12-22 19:22:41] [NOTICE] [publicarray-au] OK (DNSCrypt) - rtt: 609ms
[2019-12-22 19:22:41] [NOTICE] [publicarray-au2] OK (DNSCrypt) - rtt: 236ms
[2019-12-22 19:22:41] [NOTICE] [ibksturm] OK (DNSCrypt) - rtt: 16ms
[2019-12-22 19:22:43] [NOTICE] [publicarray-au-doh] OK (DoH) - rtt: 479ms
[2019-12-22 19:22:43] [NOTICE] [doh-ibksturm] OK (DoH) - rtt: 17ms
[2019-12-22 19:22:45] [NOTICE] [publicarray-au2-doh] OK (DoH) - rtt: 242ms
[2019-12-22 19:22:45] [NOTICE] Sorted latencies:
[2019-12-22 19:22:45] [NOTICE] -    16ms ibksturm
[2019-12-22 19:22:45] [NOTICE] -    17ms doh-ibksturm
[2019-12-22 19:22:45] [NOTICE] -   236ms publicarray-au2
[2019-12-22 19:22:45] [NOTICE] -   242ms publicarray-au2-doh
[2019-12-22 19:22:45] [NOTICE] -   479ms publicarray-au-doh
[2019-12-22 19:22:45] [NOTICE] -   609ms publicarray-au
[2019-12-22 19:22:45] [NOTICE] Server with the lowest initial latency: ibksturm (rtt: 16ms)
```

**Comment by ibksturm** [comment]
> [2019-12-22 19:22:41] [NOTICE] [publicarray-au] OK (DNSCrypt) - rtt: 609ms
> [2019-12-22 19:22:41] [NOTICE] [publicarray-au2] OK (DNSCrypt) - rtt: 236ms
> [2019-12-22 19:22:41] [NOTICE] [ibksturm] OK (DNSCrypt) - rtt: 16ms
> [2019-12-22 19:22:43] [NOTICE] [publicarray-au-doh] OK (DoH) - rtt: 479ms
> [2019-12-22 19:22:43] [NOTICE] [doh-ibksturm] OK (DoH) - rtt: 17ms
> [2019-12-22 19:22:45] [NOTICE] [publicarray-au2-doh] OK (DoH) - rtt: 242ms
> [2019-12-22 19:22:45] [NOTICE] Sorted latencies:
> [2019-12-22 19:22:45] [NOTICE] -    16ms ibksturm
> [2019-12-22 19:22:45] [NOTICE] -    17ms doh-ibksturm
> [2019-12-22 19:22:45] [NOTICE] -   236ms publicarray-au2
> [2019-12-22 19:22:45] [NOTICE] -   242ms publicarray-au2-doh
> [2019-12-22 19:22:45] [NOTICE] -   479ms publicarray-au-doh
> [2019-12-22 19:22:45] [NOTICE] -   609ms publicarray-au
> [2019-12-22 19:22:45] [NOTICE] Server with the lowest initial latency: ibksturm (rtt: 16ms)

@jedisct1 Thanks Frank for feedback

**Comment by jedisct1** [comment]
`ethservices` doesn't support HTTP/2 which is required by DoH.

**Comment by jbaker6953** [comment]
Interesting. I can't reach publicarray-au2:

```
Tracing route to ntp.seby.io [139.99.222.72]
over a maximum of 30 hops:

  1     3 ms     2 ms     2 ms  router [192.168.1.1]
  2     6 ms     4 ms     2 ms  47.149.32.1
  3     9 ms     6 ms     7 ms  172.102.104.182
  4     5 ms     4 ms     4 ms  ae8---0.scr02.lsan.ca.frontiernet.net [74.40.3.49]
  5     9 ms     5 ms     4 ms  ae1---0.cbr01.lsan.ca.frontiernet.net [74.40.3.214]
  6     *        *        *     Request timed out.
  7     6 ms     5 ms     5 ms  Cogent-level3-100G.LosAngeles1.Level3.net [4.68.73.210]
  8     8 ms     5 ms     7 ms  be3360.ccr42.lax01.atlas.cogentco.com [154.54.25.149]
  9    19 ms    16 ms    18 ms  be2932.ccr32.phx01.atlas.cogentco.com [154.54.45.161]
 10    28 ms    27 ms    27 ms  be2930.ccr21.elp01.atlas.cogentco.com [154.54.42.78]
 11    49 ms    49 ms    49 ms  be3047.ccr22.den01.atlas.cogentco.com [154.54.1.126]
 12    49 ms    48 ms    50 ms  be3036.ccr22.mci01.atlas.cogentco.com [154.54.31.90]
 13    63 ms    63 ms    64 ms  be2832.ccr42.ord01.atlas.cogentco.com [154.54.44.170]
 14    63 ms    64 ms    65 ms  be2766.ccr41.ord03.atlas.cogentco.com [154.54.46.178]
 15    63 ms    63 ms    64 ms  be100-102.chi-1-a9.il.us [198.27.73.37]
 16    80 ms    79 ms   173 ms  be100-1320.bhs-g1-nc5.qc.ca [198.27.73.206]
 17    82 ms    81 ms    81 ms  be5.bhs-vac1-a75.qc.ca [192.99.146.145]
 18    82 ms    82 ms    82 ms  bhs-vac1-a75-1-firewall.qc.ca [192.99.146.152]
 19    80 ms    81 ms    82 ms  bhs-vac1-a75-2.qc.ca [192.99.146.150]
 20    82 ms    82 ms    82 ms  bhs-vac1-a75-3.qc.ca [192.99.146.151]
 21     *        *        *     Request timed out.
 22     *        *        *     Request timed out.
 23     *        *        *     Request timed out.
 24     *        *        *     Request timed out.
 25     *        *        *     Request timed out.
 26     *        *        *     Request timed out.
 27     *        *        *     Request timed out.
 28     *        *        *     Request timed out.
 29     *        *        *     Request timed out.
 30     *        *        *     Request timed out.

Trace complete.
```
I can traceroute to ibksturm, but two different machines (Windows 10 and Linux) with dnscrypt-proxy timeout.

**Comment by jbaker6953** [comment]
Reloaded opennic.md and even though there are 12 servers listed, it appears that dnscrypt-proxy only tries 9 of them:

```
[2019-12-22 11:45:22] [NOTICE] [publicarray-au] OK (DNSCrypt) - rtt: 223ms
[2019-12-22 11:45:23] [NOTICE] [opennic-luggs2] OK (DNSCrypt) - rtt: 79ms
[2019-12-22 11:45:28] [NOTICE] [publicarray-au2] TIMEOUT
[2019-12-22 11:45:29] [NOTICE] [publicarray-au-doh] OK (DoH) - rtt: 320ms
[2019-12-22 11:45:30] [NOTICE] [opennic-luggs] OK (DNSCrypt) - rtt: 79ms
[2019-12-22 11:45:35] [NOTICE] [opennic-ethservices2] TIMEOUT
[2019-12-22 11:45:35] [NOTICE] [opennic-R4SAS] OK (DNSCrypt) - rtt: 142ms
[2019-12-22 11:45:36] [NOTICE] [publicarray-au2-doh] OK (DoH) - rtt: 306ms
[2019-12-22 11:45:41] [NOTICE] [ibksturm] TIMEOUT
[2019-12-22 11:45:41] [NOTICE] Sorted latencies:
[2019-12-22 11:45:41] [NOTICE] -    79ms opennic-luggs2
[2019-12-22 11:45:41] [NOTICE] -    79ms opennic-luggs
[2019-12-22 11:45:41] [NOTICE] -   142ms opennic-R4SAS
[2019-12-22 11:45:41] [NOTICE] -   223ms publicarray-au
[2019-12-22 11:45:41] [NOTICE] -   306ms publicarray-au2-doh
[2019-12-22 11:45:41] [NOTICE] -   320ms publicarray-au-doh
[2019-12-22 11:45:41] [NOTICE] Server with the lowest initial latency: opennic-luggs2 (rtt: 79ms)
[2019-12-22 11:45:41] [NOTICE] dnscrypt-proxy is ready - live servers: 6
```
Is this expected behavior? I see the same on both machines, so I expect it isn't a fluke.

**Comment by jedisct1** [comment]
Other ones may not match your filters.

**Comment by jbaker6953** [comment]
It's probably a different rabbit hole to investigate. I'm still curious why other people can reach servers I cannot reach.

**Comment by jedisct1** [comment]
Yes, servers are regularily tested and they get temporarily removed after having been unresponsive for too long. This is a git repository so you can see the history.

Looks like the servers not being reachable is a local issue. `ethservices` has been removed. `luggs` was already there, besides a missing copy in `public-resolvers` that has been added.

Thanks!

**Comment by ibksturm** [comment]
@jedisct1 Frank, you've got a pullrequest in opennic.md, as i see i forgot last time the opennic stamps... so i did in in the common resolver.md file but not in the opennic's one

shame on me

**Comment by jedisct1** [comment]
Shame on me, I need to find a way to sync resolvers present in multiple lists.

**Comment by ibksturm** [comment]
that's your solution:

https://s14-eu5.startpage.com/cgi-bin/serveimage?url=https%3A%2F%2Fencrypted-tbn0.gstatic.com%2Fimages%3Fq%3Dtbn%3AANd9GcQU1ojQgXkjIVwiP4AjrYybwOLDdNkB2dDAnZFxkQmKgLbvoVMkiQ%26s&sp=7a5bde85acc99d511d7ec9548f2cbb4d&anticache=508708

(German: Could an appe write shakespeare if he's got infinity time)
