### ISSUE TITLE
CZ.NIC ODVR DoH-server

### ISSUE THREAD

**Issue by black-cerberon** [DNSCrypt/dnscrypt-resolvers#224]
This public DoH server powered by CZ.NIC - czech domain registrar and Knot DNS developer
More info: https://www.nic.cz/odvr/

`sdns://AgcAAAAAAAAADDE4NS40My4xMzUuMQALb2R2ci5uaWMuY3oEL2RvaA`

**Comment by jedisct1** [comment]
Added, thanks!
