### ISSUE TITLE
Cryptostorm.is, some servers no longer up

### ISSUE THREAD

**Issue by ajp2k13** [DNSCrypt/dnscrypt-resolvers#229]
I contacted Cryptostorm because the relay  anon-cs-dk hasn't worked in a long time and got the answer that the server has been down for a while and to check which servers are alive here:

https://uptime.statuscake.com/?TestID=tZj3HbyKm5

Maybe the broken servers should be removed at least until they appear on this list again?

**Comment by jedisct1** [comment]
`cs-nl`, `cs-pl` and `cs-usdc` don't seem to be working at the moment.

They have been temporarily removed.

**Comment by ajp2k13** [comment]
cs-nl works I think? At least anon-cs-nl works I think. I know anon-cs-dk doesn't work though, hasn't for a long time now.

**Comment by jedisct1** [comment]
Maybe `cs-nl` works as a relay, but not as a server :/

I'm going to remove `anon-cs-dk` too, then. Thanks!
