### ISSUE TITLE
GeekDNS (233py.com) needs updates

### ISSUE THREAD

**Issue by imba-tjd** [DNSCrypt/dnscrypt-resolvers#236]
Homepage: https://www.nextrt.com/s/dns

DoH Servers:

* https://i.233py.com/dns-query  (for users in China)
* https://dns.233py.com/dns-query  (for users outside of China)

**Waiting for the author's reply.**

**Comment by jedisct1** [comment]
Can you tell me if you get a response about whether it is filtering or not?

**Comment by imba-tjd** [comment]
I didn't get a response.

I only see in https://github.com/DNSCrypt/dnscrypt-resolvers/commit/504b3ad48d5cb520412a4caeb04a6967a9b5b200 ，for example L846 and L870, you changed the checked status of `No filter`.

**Comment by jedisct1** [comment]
I think that was based on the description, but it would be nice to have a statement from the server maintainer.
