### ISSUE TITLE
dnscrypt.nl-ns0 is dead

### ISSUE THREAD

**Issue by black-cerberon** [DNSCrypt/dnscrypt-resolvers#241]
`dnscrypt-proxy[21180]: [dnscrypt.nl-ns0] TIMEOUT`
`dnscrypt-proxy[21180]: read udp 192.168.0.20:40680->45.76.35.212:443: i/o timeout`
`dnscrypt-proxy[21180]: dnscrypt-proxy is waiting for at least one server to be reachable`
`dnscrypt-proxy[21180]: [dnscrypt.nl-ns0] TIMEOUT`

**Comment by jedisct1** [comment]
@Yinchie  -- shoud we remove it?

**Comment by Yinchie** [comment]
Yes, Please. I am sorry. Personal circumstances.
Might return in the future.

**Comment by jedisct1** [comment]
No problem, thanks for the update!

Stay safe.
