### ISSUE TITLE
Is the JSON representation of this list still maintained?

### ISSUE THREAD

**Issue by fhemberger** [DNSCrypt/dnscrypt-resolvers#242]
I'm using `jq` to filter the list of available resolvers, using https://download.dnscrypt.info/resolvers-list/json/public-resolvers.json.

Is this JSON list still maintained or is the Markdown file in this repo the only current source?

**Comment by brahma-dev** [comment]
@fhemberger Yes. It is.

**Comment by jedisct1** [comment]
Yes!

It is automatically updated. Feel free to use it!

And you can also easily generate it yourself:

```sh
./dnscrypt-proxy -list-all -json
```

**Comment by jedisct1** [comment]
Speaking of which, it could be automatically generated in that repository, too.

I'm not too familiar with GitHub Actions yet, but it is certainly is possible to use it to trigger an action running the command above and creating a new commit with the update.
