### ISSUE TITLE
cloudflare-security not working

### ISSUE THREAD

**Issue by toddlindner** [DNSCrypt/dnscrypt-resolvers#250]
Using dnscrypt-proxy 2.0.19, cloudflare-security is not working.  PARSE_ERROR in the query log.  cloudflare works fine.

**Comment by jedisct1** [comment]
Apparently, it is returning a "permission denied" HTTP response code to some people.

Maybe due to aggressive blacklisting or to bugs. The service is still pretty new.

But it seems to work fine for the most people so we probably shouldn't remove it from the list either.

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
updated resolver in #274

**Comment by toddlindner** [comment]
Thanks, its working now!
