### ISSUE TITLE
cz.nic not working

### ISSUE THREAD

**Issue by pfactum** [DNSCrypt/dnscrypt-resolvers#262]
It looks like `cz.nic` has changed the certificate, so that the hash doesn't match anymore, because adding `cz.nic` to the list of resolvers does nothing. If I add it as a static entry with the same IP, hostname and path, it works.

Also please note there are 2 servers, `193.17.47.1` and `185.43.135.1` (it looks like the list of dnscrypt resolvers has `185.43.135.1` only). Maybe, it is also worth introducing 2 entries instead of one, saying, `cz.nic.pri` and `cz.nic.alt`.

**Comment by jedisct1** [comment]
Thank you!

The hash has been updated.
