### ISSUE TITLE
cz.nic + letsencrypt

### ISSUE THREAD

**Issue by pfactum** [DNSCrypt/dnscrypt-resolvers#265]
cz.nic resolver uses letsencrypt certificate, so it is prone to periodical hash changes.

Would it be better to drop hash from sdns for this resolver so that it works without manual intervention (as in #262)?

**Comment by jedisct1** [comment]
Let's Encrypt certificates don't change very often, so it is not worth dropping an important security feature.

They also tend to announce changes in advance, and stamps support multiple certificates simultaneously, so rotating them smoothly shouldn't be an issue.
