### ISSUE TITLE
add china dns

### ISSUE THREAD

**Issue by Potterli20** [DNSCrypt/dnscrypt-resolvers#269]
My China's DNS:
https://dns.trli.club/dns-query
tls://dns.trli.club

Other China's DNS:
https://dns.alidns.com/dns-query
tls://dns.alidns.com

**Comment by jedisct1** [comment]
Hi!

Do you have names, descriptions and DNS stamps for these?

**Comment by Potterli20** [comment]
> Hi!
> 
> Do you have names, descriptions and DNS stamps for these?

My private DNS? My DNS goes to the AD, diary of the day.

**Comment by Potterli20** [comment]
My Chinese DNS only has the correct DIG address in China, but there may be pollution abroad.

**Comment by Potterli20** [comment]
My China's DNS:
https://dns.trli.club/dns-query
tls://dns.trli.club

**Comment by Potterli20** [comment]
My China's DNS name is trli dns

**Comment by jedisct1** [comment]
Hi,

This is a personal Adguard Home instance forwarding to Cloudflare.

I'm not sure about the added value here?

**Comment by Potterli20** [comment]
> Hi,
> 
> This is a personal Adguard Home instance forwarding to Cloudflare.
> 
> I'm not sure about the added value here?

No, no, no, it's not Cloudflare, it's using IP now, with a value of 600

**Comment by jedisct1** [comment]
```sh
dnslookup resolver.dnscrypt.info https://dns.trli.club/dns-query
```

```text
resolver.dnscrypt.info.	10	IN	A	172.69.32.76
```

```sh
whois 172.69.32.76
```

```text
NetRange:       172.64.0.0 - 172.71.255.255
CIDR:           172.64.0.0/13
NetName:        CLOUDFLARENET
Organization:   Cloudflare, Inc. (CLOUD14)
OrgName:        Cloudflare, Inc.
OrgId:          CLOUD14
Address:        101 Townsend Street
City:           San Francisco
```

**Comment by Potterli20** [comment]
dig dns.trli.club

; <<>> DiG 9.16.3 <<>> dns.trli.club
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 38275
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags: do; udp: 4096
;; QUESTION SECTION:
;dns.trli.club.                 IN      A

;; ANSWER SECTION:
dns.trli.club.          600     IN      A       182.92.108.23

;; Query time: 16 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Mon Jun 29 20:19:52 CST 2020
;; MSG SIZE  rcvd: 58

**Comment by jedisct1** [comment]
But this machine doesn't have a DNS resolver, it is sending everything to Cloudflare.

You can also check this with `dnscrypt-proxy -resolve <any domain name>`.

**Comment by Potterli20** [comment]
> But this machine doesn't have a DNS resolver, it is sending everything to Cloudflare.
> 
> You can also check this with `dnscrypt-proxy -resolve <any domain name>`.

/linux-x86_64# ./dnscrypt-proxy -resolve dns.trli.club
Resolving [dns.trli.club]

Domain exists:  probably not, or blocked by the proxy
Canonical name: dns.trli.club.
IP addresses:   182.92.108.23
TXT records:    -
Resolver IP:    182.92.108.23
![Screenshot_2020-06-29-20-37-39-501_com termux](https://user-images.githubusercontent.com/28734349/86006408-7ca7ba00-ba48-11ea-97c0-516a31749b4e.jpg)

**Comment by Potterli20** [comment]
Could it be a caching problem? I have deleted Cloudflare for a week and am now in IP mode.

**Comment by Potterli20** [comment]
However, I have Cloudflare on some sites, which is a bit of a puzzle. Such as:https://dnssec.vs.uni-due.de/

**Comment by jedisct1** [comment]
Now it returns Alibaba (`123.56.93.101`).

May I suggest running the Docker image instead? https://github.com/DNSCrypt/dnscrypt-server-docker

It contains everything preconfigured.

**Comment by Potterli20** [comment]
> Now it returns Alibaba (`123.56.93.101`).
> 
> May I suggest running the Docker image instead? https://github.com/DNSCrypt/dnscrypt-server-docker
> 
> It contains everything preconfigured.

This might be something to learn

**Comment by thb007** [comment]
> Now it returns Alibaba (`123.56.93.101`).
> 
> May I suggest running the Docker image instead? https://github.com/DNSCrypt/dnscrypt-server-docker
> 
> It contains everything preconfigured.

Hello, how can you help me test this dns? https://esdns.kbsml.com/dns-query
