### ISSUE TITLE
Relays.md sign was not updated

### ISSUE THREAD

**Issue by kakawait** [DNSCrypt/dnscrypt-resolvers#272]
This morning my dnscrypt fail to start due to invalid signature for relays.md
Is related to recent changes https://github.com/DNSCrypt/dnscrypt-resolvers/commit/80270e5c807146e2f7ad7b163eca5fd4b6400778#diff-1b267619c4812cc46ee281747884ca50

And only public-resolvers.md has been signed https://github.com/DNSCrypt/dnscrypt-resolvers/commit/87df633fcf00a7f744de5a1491a5fee6e7ef73c6#diff-1b267619c4812cc46ee281747884ca50 but missing relays.md

Workaround use (latest signed relays.md from 6d ago):

https://raw.githubusercontent.com/DNSCrypt/dnscrypt-resolvers/b707e0346e8a715da40798ff6fe583dd01315a4f/v2/relays.md

**Comment by jedisct1** [comment]
Updated, thanks!
