### ISSUE TITLE
Some resolvers and relay issues.

### ISSUE THREAD

**Issue by black-ish** [DNSCrypt/dnscrypt-resolvers#276]
Hello,
I noticed recently that on some systems I'm currently in charge of that some resolvers and relays are having issues.

cs-ch, cs-lv, cs-mo, cs-ro, are incompatible with anonymization (various relays tried)
d0wn-is-ns1, d0wn-tz-ns1 seem to only function sometimes with anonymization (various relays tried)
ibksturm seems to be offline for quite a while now (resolver + relay) (UP AND RUNNING AGAIN)
charis, edoardo and suami are offline for quite some time now (resolver + relay)
dnscrypt.eu-dk and dnscrypt.eu-nl only work sometimes with anonymization (various relays tried)

I hope I'm not the only one with these issues.

**Comment by ibksturm** [comment]
hi @black-ish 

thanks for feedback it seems that i have to restart the dnsc servertask. looks like something stupid in the keyexchange skript

i will look at it this weekend

**Comment by black-ish** [comment]
No, thank you for providing it :)
Ibksturm works again! :)

**Comment by ibksturm** [comment]
@black-ish @4-FLOSS-Free-Libre-Open-Source-Software 
if youre interestet, the guys from AdGuardHome needs help with their resolverlist to

https://github.com/AdguardTeam/AdguardKnowledgeBase/blob/master/02.general/17.dns-providers/docs.en.md

@admitrevskiy is the master of it, ask him if you've got question and inputs
