### ISSUE TITLE
Invalid or unsupported stamp for meganerd-doh-ipv6

### ISSUE THREAD

**Issue by cmdpedro** [DNSCrypt/dnscrypt-resolvers#291]
There seems to be an issue with the stamp for meganerd-doh-ipv6 (from the public-resolvers). I'm getting this error:

```
dnscrypt-proxy[3331]: dnscrypt-proxy 2.0.27
dnscrypt-proxy[3331]: Network connectivity detected
dnscrypt-proxy[3331]: Source [public-resolvers.md] loaded
dnscrypt-proxy[3331]: Invalid or unsupported stamp: [sdns://AgcAAAAAAAAAJTJhMDU6ZjQ4MDoxNDAwOjQzNjo1NDAwOjJmZjpmZWI4OjhkMWMgPhoaD2xT8-l6SS1XCEtbmAcFnuBXqxUFh2_YP9o9uDgSamFyamFyLm1lZ2FuZXJkL
dnscrypt-proxy[3331]: Unable to use source [public-resolvers]: [Invalid stamp (port range)]
dnscrypt-proxy[3331]: Invalid stamp (port range)
systemd[1]: dnscrypt-proxy.service: Main process exited, code=exited, status=255/n/a
systemd[1]: dnscrypt-proxy.service: Unit entered failed state.
systemd[1]: dnscrypt-proxy.service: Failed with result 'exit-code'.
```

I rely heavily on DNSCrypt-Proxy on my server, and I believe that the program should handle this type of errors more gracefully. In my mind, the approach the program should take in this case would be to cross out this server and continue instead of exiting.

**Comment by jedisct1** [comment]
> In my mind, the approach the program should take in this case would be to cross out this server and continue instead of exiting.

This has been the case for a long time. You're just using a very old version.
