### ISSUE TITLE
Internet got cut off/disconnected everytime i do a long download

### ISSUE THREAD

**Issue by autizboyz** [DNSCrypt/dnscrypt-resolvers#304]
As the title said, i have no idea where to put this issue on so sorry if i put this on the wrong section, but i keep getting this issue everytime i download a big file that take some time to download, and also it's pretty consistent with the interval around 15-30 minute my pc connection got disconnected, i already try changing my cable (i'm using ethernet cable), but it didn't work. And i thought it was my router/modem, turn out it's not because my other pc and laptop are working fine, any idea how to fix it? Because sometime i've to download overnight due to low speed internet connection in here.

**Comment by jedisct1** [comment]
Hi!

This is a list of DNS servers.

It has nothing to do with downloads :)
