### ISSUE TITLE
ibksturm offline

### ISSUE THREAD

**Issue by black-ish** [DNSCrypt/dnscrypt-resolvers#324]
I kinda don't know where else to put this but ibksturm is down (relay + dnscrypt server).
@ibksturm can you confirm?

**Comment by jedisct1** [comment]
Offline for me as well.

Andreas, can you take a look?

**Comment by ibksturm** [comment]
hi there

i know, i do some homeworks (new rack, cablecrosses etc. and some updates)

thanks a lot for feedback

**Comment by ibksturm** [comment]
should be back know, could you check?

**Comment by black-ish** [comment]
Yes, both seem to be back up, thank you :)
