### ISSUE TITLE
add Comss.one DNS

### ISSUE THREAD

**Issue by military1** [DNSCrypt/dnscrypt-resolvers#331]
Hello!
Please add this DNSCrypt server. 
Based on Adguard Home with Unbound upstream. Dnscrypt server from github repo jedisct1. 
[Comss.one DNS](https://www.comss.ru/page.php?id=7315) - DNS with adblock filters and antiphishing, gaining popularity among russian-speaking users. 
Protocol: DNSCrypt
Addresses: [ "94.176.233.93" ]
Ports: [ 443 ]
DNSSEC	true
No filters	false
No logs	true
Provider name: 2.dnscrypt-cert.dns.comss.one
IPV4:
Stamp: sdns://AQMAAAAAAAAAETk0LjE3Ni4yMzMuOTM6NDQzIBVpyAOGbSSr5yLPYOsmU-FiMj2_q0BAdu6WiMTPzpMTHTIuZG5zY3J5cHQtY2VydC5kbnMuY29tc3Mub25l
IPV6:
Stamp: sdns://AQMAAAAAAAAAHFsyYTAyOjdiNDA6NWViMDplOTVkOjoxXTo0NDMgFWnIA4ZtJKvnIs9g6yZT4WIyPb-rQEB27paIxM_OkxMdMi5kbnNjcnlwdC1jZXJ0LmRucy5jb21zcy5vbmU

**Comment by jedisct1** [comment]
Added, thank you!

**Comment by military1** [comment]
Thank you very much. But it seems for ipv6 added the same as for ipv4?

**Comment by jedisct1** [comment]
Oops, you're right! This has been fixed, sorry for that!
