### ISSUE TITLE
Request for adding DNSPod DoH

### ISSUE THREAD

**Issue by bososha** [DNSCrypt/dnscrypt-resolvers#335]
Name: dnspod-doh
Info page: https://www.dnspod.cn/Products/Public.DNS?lang=en
Description: A public DNS resolver in mainland China provided by DNSPod (Tencent Cloud), with the support of DoH and DoT
PS. The DoH/DoT service of DNSPod DNS is now under beta test, no official document post in the info page.

sdns://AgAAAAAAAAAAACDrdSX4jw2UWPgamVAZv9NMuJzNyVfnsO8xXxD4l2OBGAdkb2gucHViCi9kbnMtcXVlcnk

**Comment by jedisct1** [comment]
Added, thanks!
