### ISSUE TITLE
Add East.Comss.one

### ISSUE THREAD

**Issue by military1** [DNSCrypt/dnscrypt-resolvers#344]
Hello!
Please add this DNSCrypt server.
Based on Adguard Home with Unbound upstream. Dnscrypt server from github repo jedisct1.
[East.Comss.one](https://www.comss.ru/page.php?id=7315) DNS - DNS with adblock filters and antiphishing, gaining popularity among russian-speaking users.
Protocol: DNSCrypt
Addresses: [ "91.230.211.67" ]
Ports: [ 5443 ]
DNSSEC true
No filters false
No logs true
Provider name: 2.dnscrypt-cert.dns.east.comss.one
IPV4:
Stamp: sdns://AQMAAAAAAAAAEjkxLjIzMC4yMTEuNjc6NTQ0MyAVacgDhm0kq-ciz2DrJlPhYjI9v6tAQHbulojEz86TEyIyLmRuc2NyeXB0LWNlcnQuZG5zLmVhc3QuY29tc3Mub25l
No IPV6

**Comment by mibere** [comment]
You should follow the usual procedure. Fork the repo, add your server and create a pull request.

**Comment by military1** [comment]
@mibere 
Please tell me in more detail. So I forked and specified the parameters used.
https://github.com/military1/encrypted-dns-server

**Comment by mibere** [comment]
You forked the wrong repository, you have to fork [DNSCrypt/dnscrypt-resolvers](https://github.com/DNSCrypt/dnscrypt-resolvers), modify the file _v3/public-resolvers.md_ and/or _v3/relays.md_ and [create a pull request](https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request).

**Comment by ianbashford** [comment]
I'm not sure how familiar you are with git, but here's a short command line workflow for you. There are probably a few ways to do this so it's not intended to be a definitive guide to git, just a quick start to get you going...  hope this helps

```
<Fork dnscrypt/dnscrypt-resolvers in githhub web interface>

## clone the repo to your local machine
» git clone git@github.com/military1/dnscrypt-resolvers.git

» cd dnscrypt-resolvers 

## this creates a branch for your changes
» git checkout -b create-eastcomssone

<edit v3/public-resolvers.md and/or v3/relays.md>

## this will show you the changed files - some sample output is shown
» git status

On branch create-eastcomssone
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   v3/public-resolvers.md

no changes added to commit (use "git add" and/or "git commit -a")

## commit your changes - some sample output is shown -m adds a commit message. If you edit both files, you can put them both on this line after the commit message.
» git commit v3/public-resolvers.md -m'created eastcomssone'
[create-eastcomssone e9e6164] created eastcomssone
 1 file changed, 1 insertion(+), 1 deletion(-)

## push your changes back to YOUR github repo using the same branch created earlier
» git push origin create-eastcomssone


You can then start the Pull Request process from your repo to upstream
```
