### ISSUE TITLE
ibksturm SERVFAIL

### ISSUE THREAD

**Issue by black-ish** [DNSCrypt/dnscrypt-resolvers#346]
Hi,
Since a few days ago ibksturm throws only "SERFAIL -- Invalid DNSSEC signature received or server may be experiencing connectivity issues" out, am I alone or can someone confirm?

**Comment by ibksturm** [comment]
Wunderfull good Morning and thanks for your question

My Router is going to die, yesterday i recived the sparepart, but this morning sparepart goes down too... situation makes me not lucky, but i know the problem

it‘s not the answer you wan‘t to read, i know, but thats everything i can sa at the moment

greets and stay health

**Comment by black-ish** [comment]
Thank you for the information, No worries that already helps. Sad to hear that your router is dying, I wish you luck in solving it :)

**Comment by ibksturm** [comment]
update: 

on router (edge router x) runs openwrt 19.07.4 (it sucks)

3 hours ago i installed back OW 19.07.3, it seams its more stable (i‘m in homenetwork drive by wireshark)

update de la muerte, need absolutly newer hardware

**Comment by black-ish** [comment]
I'm guessing you haven't been able to resolve it as of yet? I just tried it again and still get a SERVFAIL.
No hurry, would just like an update if possible ;)

**Comment by ibksturm** [comment]
@black-ish could you please close

**Comment by black-ish** [comment]
Closed as per request, but as of this post is not fixed.
