### ISSUE TITLE
stamp for opennic-fische wrong?

### ISSUE THREAD

**Issue by random-user-random** [DNSCrypt/dnscrypt-resolvers#351]
I had server fails with opennic-fische and looking up the ipv4 sdns doesn't match
https://download.dnscrypt.info/resolvers-list/v2/public-resolvers.md
https://servers.opennic.org/edit.php?srv=ns21.de.dns.opennic.glue

**Comment by jedisct1** [comment]
Thank you!

The stamp was indeed incorrect. Additionally, it is not reachable over IPv6.

Fixed, thanks!
