### ISSUE TITLE
trashvpn.de maintenance / downtime

### ISSUE THREAD

**Issue by zzzkeil** [DNSCrypt/dnscrypt-resolvers#36]
Hi, 
i plan server maintenance with a longer downtime, for the dnscrypt service.
It may take a little longer than usual ( 2 or 3 weeks ) 
I test a few things with the server. 
Maintenance / Downtime start in > 3 Days
Removing the following server from the list is maybe necessary.
It´s my ipv4 server : trashvpn
dnscrypt-server Docker image : DNSSEC/Non-logged/Uncensored Hosted in Germany
sdns://AQcAAAAAAAAAEzM3LjIyMS4xOTUuMTgxOjg0NDMgeWFZIMbyef83QDyIdD3cE9Fe_4QcTDw4nKWJDSacGvYbMi5kbnNjcnlwdC1jZXJ0LnRyYXNodnBuLmRl

Thanks

**Comment by jedisct1** [comment]
Hi!

And thanks for the heads up!

No problem, I'm gonna temporarily remove it. Good luck setting up the new server!
