### ISSUE TITLE
Google DOH server doesn't work

### ISSUE THREAD

**Issue by willianberf** [DNSCrypt/dnscrypt-resolvers#37]
Hi,
Google developers page on [DOH](https://developers.google.com/speed/public-dns/docs/dns-over-https) doesn't have the /experimental API anymore.
Also, when I tried to use dnscrypt with the /resolve API as a static server, dnscrypt skips it from server list.

**Comment by jedisct1** [comment]
" Last updated July 21, 2016. "

This web page doesn't seem to be up to date.

Google seems to be accessible just fine with the current stamp, so the issue you are experiencing might be unrelated. Maybe some firewall configuration?
