### ISSUE TITLE
What blocklist is being used on Jitender's own DDNS?

### ISSUE THREAD

**Issue by jenabaivab** [DNSCrypt/dnscrypt-resolvers#398]
@coolquasar Could I ask what blocklist(s) is/are being used in your DNS resolver (https://jit.ddns.net/dns-query)?
Also, is there a DoT implementation of it, that can be used for Android Devices?

**Comment by coolquasar** [comment]
@jenabaivab 

Absolutely. 

1. Here are the blocklists - https://hastebin.com/kasivemaru.less
2. DoT implementation - Yes, here is the URL ----> **_tls://jit.ddns.net_**

In addition to DoT, the following protocols are supported
1. DNSCrypt - port 443
2. DoH - https://jit.ddns.net/dns-query (Shares port 443 with DNSCrypt)
3. DoQ - quic://jit.ddns.net:786

I hope it helps. I would be happy to address additional questions

**Comment by jenabaivab** [comment]
Thank you so much for the response. All I needed to know was the inclusion of OISD blocklist.
The DoH implementation is faster than even cloudflare for me here in Odisha. It's amazing really.

Also, doesn't OISD already include so many lists that are included in the above link already? He handles a lot of false positives from all the lists too. Will imposing the same rules not increase chances of slowdowns? 
Additionally, where should I report false positives if I encounter any? Reddit, telegram, email, github repo with issues enabled?

**Comment by coolquasar** [comment]
@jenabaivab 

Great to hear that my DNS server is providing quicker responses. Thanks for using it. 

I evolved the blocklist in an order, where OISD wasn’t the first list I added. So I continued to keep all the lists together and leave it to the program to determine unique block lists. With that said, I hadn’t seen any noticeable difference in performance when processing queries. Although, it has impact when refreshing the blocklist, as it takes longer due to the list being long. I am willing to live with that unless it becomes a negative experience. 

@coolquasar in Reddit or github are quick to reach me for any false positives. I would be happy to get it working for you

**Comment by jenabaivab** [comment]
Thanks a ton!

At the risk of sounding stupid, I am just gonna ask one more question. I usually use either NextDNS or Cloudflare on my devices. More often than not, they can resolve even blocked websites when being used with DNS over HTTPS. So far, I haven't been able to achieve that with this DNS. Is there a specific reason why those services can unblock without any speed difference inspite of the same DoH protocol? Really looking forward to learn something here.

**Comment by coolquasar** [comment]
@jenabaivab 

Thanks for reaching out. 

Is your question, you are seeing differences in DNS blocking when using conventional vs DoH with NextDNS or Cloudflare ?

If that is the case, I won’t be able to comment on their implementation. Ideally, such a difference wouldn’t exist. 

In my implementation, the block lists are independent of the protocol (in this case DoH) that is used to query the DNS server. DoH or DoT protocols help securely carry DNS query and response. The same set of block list will equally apply to queries requested through all protocols. The client shouldn’t see different in blocklist due to the protocol being used. I hope it answers your question.

**Comment by jenabaivab** [comment]
No problem, thank you again for being so patient with me.
This was really helpful.
And Happy New Year 😄

**Comment by coolquasar** [comment]
You are welcome. I hope you have a good time using the DNS server. Happy new year to you too!

**Comment by jenabaivab** [comment]
@coolquasar Hello again!
Unfortunately, I seem to be getting quite a lot of false positives in different services :/
I use Sync for Reddit app and many images are missing from there. A few websites also report half loaded content. Sometimes I get 'io exception' error while browsing reddit via sync too. Also, I got ads once in an app that is usually blocked by OISD alone, since I have used it previously(happened just once though). The main issue though is ton of slowdowns.
Obviously I am not a smug idiot who is going to tell you how to run your own DNS, I just wish there were some fewer lists. I used to run NextDNS official list, notracking, and OISD, never saw anything or got any slowdowns. It's the perfect combo imo. But like you said above, I understand why you use the no of lists you use. Just thougt I'd let you know that I was indeed facing problems with daily browsing. No hate, just informing that's all. Very sorry if I come off as offensive, nagging about a free service.

**Comment by coolquasar** [comment]
@jenabaivab 

I am sorry, you are having negative experience. The list has been working well for the users so far. I am willing make change. If you are interested, please try and provide your feedback. If you didn't want to try, that is ok as well, I understand

Here is the list of adblocks enabled now

http://sysctl.org/cameleon/hosts
http://phishing.mailscanner.info/phishing.bad.sites.conf
https://gitlab.com/quidsup/notrack-blocklists/raw/master/notrack-malware.txt
https://gitlab.com/quidsup/notrack-blocklists/raw/master/notrack-blocklist.txt
https://raw.githubusercontent.com/deathbybandaid/piholeparser/master/Subscribable-Lists/ParsedBlacklists/AdAway-Default-Blocklist.txt
https://v.firebog.net/hosts/Easyprivacy.txt
https://raw.githubusercontent.com/pirat28/IHateTracker/master/iHateTracker.txt
https://raw.githubusercontent.com/deathbybandaid/piholeparser/master/Subscribable-Lists/ParsedBlacklists/CryptoWall-Ransomware-C2-Domain-blocklist.txt
https://zerodot1.gitlab.io/CoinBlockerLists/hosts
https://dbl.oisd.nl
https://raw.githubusercontent.com/r-a-y/mobile-hosts/master/AdguardDNS.txt
https://raw.githubusercontent.com/XionKzn/PiHole-Lists/master/PiHole/Archive/Quad9.txt
https://raw.githubusercontent.com/Perflyst/PiHoleBlocklist/master/android-tracking.txt
https://raw.githubusercontent.com/Perflyst/PiHoleBlocklist/master/SmartTV.txt
https://raw.githubusercontent.com/DandelionSprout/adfilt/master/Alternate%20versions%20Anti-Malware%20List/AntiMalwareHosts.txt
https://s3.amazonaws.com/lists.disconnect.me/simple_malvertising.txt

**Comment by jenabaivab** [comment]
@coolquasar really sorry for the late response, it's been a very busy month for me. 
I just re-enabled your DNS on my windows and android. If I have the nerve to complain, I should have the sense to test it too.
I'll definitely let you know if I face the same issues again. Just have to use it for a day to understand.
Thank you so much for the response.

**Comment by jenabaivab** [comment]
@coolquasar please let me know if you need anything else to test, i'll keep reporting FPs if I find any.

**Comment by coolquasar** [comment]
@jenabaivab 
I just saw your posts, I was bit offline last couple of weeks. I will review your request and get back shortly

**Comment by coolquasar** [comment]
sports24, windows updatestar, hotspotshield- added as whitelist

block list - I will continue to review them as part of the maintenance effort 

google amp page - it loads for me. Provide me an URL that doesn’t work. I will check again 

I hope it helps. Let me know if any questions

**Comment by jenabaivab** [comment]
https://streamable.com/e4gztb

@coolquasar have a look at this. Works fine with other adblocking dns services.

**Comment by coolquasar** [comment]
@jenabaivab 

great, thanks. Google amp pages should work now. Please check and let me know

**Comment by jenabaivab** [comment]
@coolquasar yup, working fine now, thank you! Just a few things to ask.

1. Is it possible to add DNS Rebinding protection please? I have deflected 3 such attempts in the last month alone with NextDNS, but now it is having trouble working alongside Jio Fiber.
2. Highly suggest allowing users to open issues in your forked repository of this project so that it's easier for everyone to separate the DNSCrypt project and your DNS issues.

**Comment by jedisct1** [comment]
If I may: DNS rebinding can be blocked locally with `dnscrypt-proxy`. See the documentation: https://github.com/DNSCrypt/dnscrypt-proxy/wiki/Filters#dns-rebinding-protection

Doing it unconditionally at server level does more harm than good. It breaks connections to local routers, email SPAM checkers, etc.

**Comment by jenabaivab** [comment]
@jedisct1 thank you for the suggestion. Unfortunately, I am looking for a DoT solution on Android PrivateDNS. So server-side is the only option there.

**Comment by jenabaivab** [comment]
@coolquasar found a false positive. Is it possible for you to enable the 'Issues' section on your forked repo of DNSCrypt? Reporting here isn't the most ideal solution I would say since the purpose of this project is different.

**Comment by coolquasar** [comment]
@coolquasar in Reddit is a quick way to reach me as well. Please let me know the false positive in Reddit, meanwhile I will create a forked repo. Thankyou

**Comment by jenabaivab** [comment]
The team logos on top of nbastream.tv are blocked. 
I contacted OISD dev, he said that it's fixed. Maybe it's still being blocked by some other lists.

**Comment by coolquasar** [comment]
@jenabaivab 

Team logos for nbastream.tv is fixed now, please check. Let me check the other items shortly

**Comment by jenabaivab** [comment]
@coolquasar checked, nbastream logos now load properly.

**Comment by coolquasar** [comment]
@jenabaivab 

forms.gle and google image search issues are resolved, please check and let me know

**Comment by jenabaivab** [comment]
@coolquasar confirmed, both working as expected now.

**Comment by jenabaivab** [comment]
@coolquasar don't know if you have had time to check yet, but logos are still missing on sports24.club

PS - waiting on the forked/new repo to report further issues
