### ISSUE TITLE
all ibksturm servers

### ISSUE THREAD

**Issue by ibksturm** [DNSCrypt/dnscrypt-resolvers#404]
hi @jedisct1 

first i wish you a health and happy new year

all 3 servers and both relays from me are currently down till april... wife kicked me out, at this place i havdn‘t got acceptable internet connection, but in april things gonna be better. i‘ll do a pull request when i‘m back, i promise

greeeets from snowing switzerland

**Comment by ibksturm** [comment]
ibks

**Comment by jedisct1** [comment]
Hi Andreas,

Sorry to hear that :( Life can suck really big time in unpredictable ways :(

The servers should really be the last of your worries.

Good luck. Stay strong!

**Comment by ibksturm** [comment]
> Hi Andreas,
> 
> Sorry to hear that :( Life can suck really big time in unpredictable ways :(
> 
> The servers should really be the last of your worries.
> 
> Good luck. Stay strong!

hi Frank

yeah, Karma is a bitch with red lips and golden hair... no server are at a far away position, first i need to handle with court and working situation and my own life and so on

well read together! 

greets 

andi
