### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Heptazhou** [DNSCrypt/dnscrypt-resolvers#412]
how could "linuxsec-adguard" be marked as "nofilter" and "with blocker" at the same time?

#411:

> Non-logging DoH with malware and ad blocker. Resolver located in the Indonesia. Operated by LinuxSec.

> sdns://AgcAAAAAAAAADDEwMy44NS4xNS42MCAyhv9lpl-vMghe6hOIw3OLp-N4c8kGzOPEootMwqWJiBBkb2gubGludXhzZWMub3JnCC9hZGd1YXJk

```json5
{ name: "linuxsec-adguard", proto: "DoH", ipv6: false, addrs: ["doh.linuxsec.org", "103.85.15.60"], ports: [443], dnssec: true, nolog: true, nofilter: true, description: "Non-logging DoH with malware and ad blocker. Resolver located in the Indonesia. Operated by LinuxSec.\nhttps://doh.linuxsec.org", stamp: "sdns://AgcAAAAAAAAADDEwMy44NS4xNS42MCAyhv9lpl-vMghe6hOIw3OLp-N4c8kGzOPEootMwqWJiBBkb2gubGludXhzZWMub3JnCC9hZGd1YXJk" }
```

**Comment by jedisct1** [comment]
Hi!

`nofilter` means that the resolver doesn't block domains, so if the service is blocking ads, it shouldn't be `nofilter`  :)

**Comment by Heptazhou** [comment]
#413-[R1584](https://github.com/DNSCrypt/dnscrypt-resolvers/pull/413/files#diff-abc72db94b9e4fb7edb1d856ce7ac3267fffb0501488cb79131591b25b7771b2R1584):

> Non-logging, AD-filtering, supports DNSSEC.

well, then not only "linuxsec-adguard", "linuxsec-doh" is also blocking ads?
but "linuxsec-doh"'s stamp says `nofilter` as always.

**Comment by jedisct1** [comment]
Additionally, these are not resolvers. Just frontends forwarding to Cloudflare :/

**Comment by Heptazhou** [comment]
indeed. but just couldnt ignore it.

anyway, thanks for you time! :)
