### ISSUE TITLE
Stamp for Onion Cloudflare is failing sig checks.

### ISSUE THREAD

**Issue by alecmuffett** [DNSCrypt/dnscrypt-resolvers#439]
Hiya!

In https://github.com/DNSCrypt/dnscrypt-resolvers/blob/master/v3/onion-services.md

The given stamp 

`sdns://AgcAAAAAAAAAACC0WWFtenR5met-s8i0oiShMtYstulWSybPBq-zBUEMNT5kbnM0dG9ycG5sZnMyaWZ1ejJzMnlmM2ZjN3JkbXNiaG02cnc3NWV1ajM1cGFjNmFwMjV6Z3FhZC5vbmlvbgovZG5zLXF1ZXJ5`

Is failing checks, with the result:
```
[onion-cloudflare] does not support HTTP/2
[onion-cloudflare] Certificate hash [b459616d7a747999eb7eb3c8b4a224a132d62cb6e9564b26cf06afb305410c35] not found
```

Given the nature of Onion Networking - that is contains an inbuilt cryptographic check - I would recommend changing the stamp to read:

`sdns://AgcAAAAAAAAAAAA-ZG5zNHRvcnBubGZzMmlmdXoyczJ5ZjNmYzdyZG1zYmhtNnJ3NzVldWozNXBhYzZhcDI1emdxYWQub25pb24KL2Rucy1xdWVyeQ`

...and skip the certificate fingerprinting, leaving that to TLS?

**Comment by jedisct1** [comment]
Thanks Alex,

This is the first time that certificate changes, but you're right, for onion services, this is not really required.

The stamp has been updated. Thanks!
