### ISSUE TITLE
Cleanbrowsing security filter

### ISSUE THREAD

**Issue by Snapy** [DNSCrypt/dnscrypt-resolvers#44]
Cleanbrowsing has a new DoH resolver for filtering phishing, malware and malicious domains only ([link](https://cleanbrowsing.org/dnsoverhttps)) but I don't know if it supports DNSCrypt. Can you add them/it ?

**Comment by jedisct1** [comment]
They are already in the list (`doh-cleanbrowsing-family`, `doh-cleanbrowsing-adult`).

You can also access them using DNSCrypt (`cleanbrowsing-family` and `cleanbrowsing-adult`) which is likely to be faster.

**Comment by Snapy** [comment]
I disagree. The first one listed is not there.  
> Security Filter

Our security blocks access to phishing, malware and malicious domains. It does not block adult content.

URLs: https://doh.cleanbrowsing.org/doh/security-filter/

**Comment by jedisct1** [comment]
You should have mentioned what I was supposed to look at :)

Added, thanks!

**Comment by Snapy** [comment]
Looks like the description is wrong. It does not block any adult/porn/proxy stuff (unless it's malware). Also I don't know if you checked for its dnscrypt equivalent (not explicitly mentioned ; maybe ping them on Twitter).
