### ISSUE TITLE
CIRA dns servers

### ISSUE THREAD

**Issue by skhan85** [DNSCrypt/dnscrypt-resolvers#442]
Hi why only CIRA-Family dns is available with DNSCRYPT. CIRA has two other servers too: CIRA Private and CIRA Protect. But using e.g. CIRA-Protect in the .toml file doesn’t work. Using Raspberry PI. 

https://www.cira.ca/node/8331

**Comment by jedisct1** [comment]
CIRA servers are very buggy.

They are the only ones that only support a minimal set of query parameters, and they if the EDNS-clientsubnet option is used, they are unable to process the query and return a `REFUSED` response.

So, if they are in the list like other servers, queries will randomly fail when CIRA is being chosen.

It would be good to have them back. Maybe once these bugs are finally fixed.
