### ISSUE TITLE
dnscrypt.ca-2-ipv6 stamp change

### ISSUE THREAD

**Issue by dnscrypt-ca** [DNSCrypt/dnscrypt-resolvers#448]
Server had to be relocated, IPv6 address changed, please update stamp to:

sdns://AQcAAAAAAAAAJVsyNjA3OjUzMDA6NjE6OTVmOjcyODM6MTFkOTpmODY6ZTY5MF0gmHxwqJfb2hUaNK1LVeqADvVhzASq1cV90sPYYfwX9CkiMi5kbnNjcnlwdC1jZXJ0LmRuc2NyeXB0LmNhLTItaXB2Ng

Thanks,
s.

**Comment by jedisct1** [comment]
Thanks!

Could you check the DoH server as well? That one returns a 502 error code.

**Comment by dnscrypt-ca** [comment]
Thanks Frank!  I restarted the listener, are you still getting a 502?

**Comment by jedisct1** [comment]
All good now! Thank you!
