### ISSUE TITLE
Add Mullvad servers

### ISSUE THREAD

**Issue by yitzhaq** [DNSCrypt/dnscrypt-resolvers#453]
Would you be willing to add Mullvad's new DoH servers?

https://mullvad.net/en/help/dns-over-https-and-dns-over-tls/

Announcement:

https://mullvad.net/en/blog/2021/3/3/mullvad-doh-and-dot-beta-release/

Cheers

**Comment by jedisct1** [comment]
For a VPN service, it's a little bit sad that they don't support DNSCrypt, that would allow anonymization.

Can you send a pull request with names, descriptions and stamps for the DoH server?

**Comment by yitzhaq** [comment]
I've taken a stab at it. Hope I didn't miss the mark too badly..

**Comment by jedisct1** [comment]
But really, it would be better if you could test  :)

**Comment by jedisct1** [comment]
Merged, thank you!

**Comment by yitzhaq** [comment]
Thanks for the quick merge!
A few marginally related questions:

* As mentioned I used hostname instead of addr. However I noticed that for some entries (such as Cloudflare), 1.0.0.1 was used instead of one.one.one.one. In the case of Cloudflare, that means 1.1.1.1 is seemingly not used at all, which seems suboptimal. Is this intentional, and does the stamps spec support >1 addr entry in a single stamp, as I understand it does for hashes?
* Is there a preference for using addr instead of hostname, or is there another reason for not using eg. one.one.one.one?
* Again looking at the Cloudflare example, one possible benefit could be that this allows for splitting up IPv4 and IPv6 into separate entries. Is this desirable? Like Cloudflare's one.one.one.one, Mullvad's hostnames have both A and AAAA records.
* I also noticed the Cloudflare entry did not appear to have a hash? Is there a particular reason for this, and do you prefer to have (or not have) hashes in the stamps?

Depending on the above answers, I can adjust the Mullvad entries as preferred (if needed).

**Comment by jedisct1** [comment]
A name is always required. This is the name used for SNI, i.e. for the server to know what HTTP service you are accessing.

It is only also used as a host name if no IP address is provided.

If the server has a stable IP address, the IP should always be provided. Without an IP, DoH requires a horrible hack where another server needs to be accessed insecurely ("fallback resolver")  in order to know the address of the actual DNS server.

But if the IP addresses changes constantly, unfortunately, using a fallback server is inevitable.

Hashes are important for security. They were removed for Cloudflare because they are changing their certificates constantly, and without any prior notice.

**Comment by yitzhaq** [comment]
Right, thanks.

So the remaining questions then are:

* Is there a valid/proper way to provide >1 IP in a stamp, and if not, how should one handle the case where a service has >1 IP (like Cloudflare and Mullvad)
* Is it desirable to split up an entry with both A and AAAA to separate IPv4 and IPv6 entries, such as what's been done for Cloudflare?
* If the Mullvad entries should *not* be split up, but left as they are today, should they be renamed -ipv6, or is that intended to signify entries with *only* IPv6 rather than entries that *support* IPv6?

Common wisdom suggests Happy Eyeballs usually tends to be the way to go, but if there are good reasons to separate out IPv6, I don't currently see a way to do that without sacrificing the redundancy of having multiple IPs where a service supports it (such as the Cloudflare IPv4 entry lacking 1.1.1.1, and having only 1.0.0.1).

**Comment by jedisct1** [comment]
> Is there a valid/proper way to provide >1 IP in a stamp

I don't know! Need to check.

But a single entry can have multiple stamps.

> Is it desirable to split up an entry with both A and AAAA to separate IPv4 and IPv6 entries, such as what's been done for Cloudflare?

Yes! So that people can choose if they want to use IPv4 and/or IPv6 for individual servers. The convention is to have an `-ipv6` suffix for servers to over IPv6.

>  Cloudflare IPv4 entry lacking 1.1.1.1

That's a very specific case. `1.1.1.1` is not always reachable, as the address is still used by some routers, so we only include the one that works on more networks.

**Comment by yitzhaq** [comment]
> > Is there a valid/proper way to provide >1 IP in a stamp
> 
> I don't know! Need to check.
> 
> But a single entry can have multiple stamps.

Oh, that's interesting!
So in principle, there could be 2 entries both named "mullvad", with individual stamps where only the (single) IP differ? What decides which one of them gets used, is RTT calculation performed on all of them or is there a simple round-robin principle or what?

> > Is it desirable to split up an entry with both A and AAAA to separate IPv4 and IPv6 entries, such as what's been done for Cloudflare?
> 
> Yes! So that people can choose if they want to use IPv4 and/or IPv6 for individual servers. The convention is to have an `-ipv6` suffix for servers to over IPv6.

Alright, I'll update and split it up, depending on the answer to the previous question.

> > Cloudflare IPv4 entry lacking 1.1.1.1
> 
> That's a very specific case. `1.1.1.1` is not always reachable, as the address is still used by some routers, so we only include the one that works on more networks.

I see. While I know Cloudflare did extensive testing before launching (including with RIPE's Atlas program - I observed the tests carried out on my own probe), and made a significant outreach effort, there are probably still ASes or routers out there which fail to route it properly.
So disregarding this corner case, the convention would be to define each server (or rather, each IP) as an individual entry, and group them by name as described above?
