### ISSUE TITLE
LavaDNS

### ISSUE THREAD

**Issue by black-cerberon** [DNSCrypt/dnscrypt-resolvers#468]
Add LavaDNS (DoH) - https://dns.lavate.ch/

 _LavaDNS is a free DNS service hosted by LavaTech, the pioneers in the friend cloud space.
There's no logging, no ECS, no filtering. DNSSEC is verified and enforced. We support OpenNIC. There are ratelimits in place._

Helsinki, Finland 🇫🇮
v4 DoH: `sdns://AgcAAAAAAAAAETk1LjIxNy4yNS4yMTc6NDQzID4aGg9sU_PpekktVwhLW5gHBZ7gV6sVBYdv2D_aPbg4EWV1MS5kbnMubGF2YXRlLmNoCi9kbnMtcXVlcnk`
v6 DoH: `sdns://AgcAAAAAAAAAGlsyYTBkOjFhNDM6YzAxMDoxMzU6Ol06NDQzID4aGg9sU_PpekktVwhLW5gHBZ7gV6sVBYdv2D_aPbg4EXVzMS5kbnMubGF2YXRlLmNoCi9kbnMtcXVlcnk`

California, USA 🇺🇸 
v4 DoH: `sdns://AgcAAAAAAAAAETc5LjExMC4xNzAuNDM6NDQzID4aGg9sU_PpekktVwhLW5gHBZ7gV6sVBYdv2D_aPbg4EXVzMS5kbnMubGF2YXRlLmNoCi9kbnMtcXVlcnk`
v6 DoH: `sdns://AgcAAAAAAAAAGlsyYTBkOjFhNDM6YzAxMDoxMzU6Ol06NDQzID4aGg9sU_PpekktVwhLW5gHBZ7gV6sVBYdv2D_aPbg4EXVzMS5kbnMubGF2YXRlLmNoCi9kbnMtcXVlcnk`

**Comment by ibksturm** [comment]
hi there

please do a pull request in

https://github.com/DNSCrypt/dnscrypt-resolvers/blob/master/v3/public-resolvers.md

greets
