### ISSUE TITLE
Zackptg5 unreachable

### ISSUE THREAD

**Issue by Zackptg5** [DNSCrypt/dnscrypt-resolvers#472]
Fixed my dnscrypt server. Made the mistake of updating docker and it threw me in for a loop, all resolved now 

Edit: Actually, scratch that. I'm getting a read udp error, any ideas as to why? I changed nothing but updating docker

**Comment by Zackptg5** [comment]
Actually, scratch that. It seems that --net=host no longer works. Any tips for why?

**Comment by jedisct1** [comment]
Damn. Can you check if the container itself is still running even though connections are not served any more?

**Comment by Zackptg5** [comment]
Ya, started without error and was running. But lsof shows no 443 port activity. I'm going to try a fresh install with same keys and see what happens

**Comment by Zackptg5** [comment]
Installed on new instance and getting the exact same error:
`read udp [<guest ip>]:36065->[<server ip>]:443: i/o timeout`

**Comment by jedisct1** [comment]
Maybe some firewall rules (`nftables`, `iptables`) got installed during the update?

**Comment by Zackptg5** [comment]
I was thinking that but I use ufw and nothing changed there. The fact that the clean install did the same thing and that everything worked fine after updating but then crapped a couple days later on it's own makes me think it's a vultr issue. Hopefully I get this figured out

**Comment by jedisct1** [comment]
Oops, the issue may not be you.

Can you try again, after updating the Docker image?

**Comment by jedisct1** [comment]
(long story short: the docker image was updated for Ubuntu 21.04, but looks like Ubuntu screwed up and broke things)

**Comment by Zackptg5** [comment]
LOL
Works now. I'm on debian 10 btw. Thanks man!

**Comment by Zackptg5** [comment]
Also, I noticed that watchtower docker image is installed and running too. Is that needed since the dnscrypt image is set to auto restart?

**Comment by jedisct1** [comment]
Sorry for that. I'm going to re-add your server of course.

**Comment by Zackptg5** [comment]
This is why I use debian for server related stuff haha. No problem, thanks for all your hard work!
