### ISSUE TITLE
New Cryptostorm servers only work with relays for short time.

### ISSUE THREAD

**Issue by black-ish** [DNSCrypt/dnscrypt-resolvers#474]
Hi, I have come across this issue with all newly added CS servers which seem to only work for a limited time when used with relays.
After some time, say around an hour, they just just error with SERVER_TIMEOUT.
Can somebody replicate this?

I already tried to use the force_tcp option to only try it with tcp instead of udp but it's the same behaviour.
Timeout is set for 20000, but it never takes that long to throw the error from trying to to resolve dns to timeout, so my guess is that something is maybe not configured correctly?

Regards

**Comment by EsEnZeT** [comment]
Saw something similar, I was gething SERV_FAIL / network_error only with cs-* servers. Because of the lack of time I disabled all of them.
