### ISSUE TITLE
Rubyfish can be used normally

### ISSUE THREAD

**Issue by toorich** [DNSCrypt/dnscrypt-resolvers#482]
Test link: [UW](https://uw-dns.rubyfish.cn/dns-query?name=google.com) or [EA](https://ea-dns.rubyfish.cn/dns-query?name=google.com).

**Comment by jedisct1** [comment]
They still look quite broken. Yesterday, both returned `503` error codes, and now, they return empty responses:

```sh
dnslookup example.com sdns://AgEAAAAAAAAAAKA-GhoPbFPz6XpJLVcIS1uYBwWe4FerFQWHb9g_2j24OCAyhv9lpl-vMghe6hOIw3OLp-N4c8kGzOPEootMwqWJiBJ1dy1kbnMucnVieWZpc2guY24KL2Rucy1xdWVyeQ
```

```text
dnslookup result:
;; opcode: QUERY, status: NOERROR, id: 57780
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; QUESTION SECTION:
;example.com.	IN	 A

;; ADDITIONAL SECTION:

;; OPT PSEUDOSECTION:
; EDNS: version 0; flags: ; udp: 4096
```

No IP address for `example.com`?

Same response with `sdns://AgEAAAAAAAAAAKA-GhoPbFPz6XpJLVcIS1uYBwWe4FerFQWHb9g_2j24OCAyhv9lpl-vMghe6hOIw3OLp-N4c8kGzOPEootMwqWJiBJlYS1kbnMucnVieWZpc2guY24KL2Rucy1xdWVyeQ`.

**Comment by toorich** [comment]
> They still look quite broken. Yesterday, both returned `503` error codes, and now, they return empty responses:
> 
> ```shell
> dnslookup example.com sdns://AgEAAAAAAAAAAKA-GhoPbFPz6XpJLVcIS1uYBwWe4FerFQWHb9g_2j24OCAyhv9lpl-vMghe6hOIw3OLp-N4c8kGzOPEootMwqWJiBJ1dy1kbnMucnVieWZpc2guY24KL2Rucy1xdWVyeQ
> ```
> 
> ```
> dnslookup result:
> ;; opcode: QUERY, status: NOERROR, id: 57780
> ;; flags: qr aa rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1
> 
> ;; QUESTION SECTION:
> ;example.com.	IN	 A
> 
> ;; ADDITIONAL SECTION:
> 
> ;; OPT PSEUDOSECTION:
> ; EDNS: version 0; flags: ; udp: 4096
> ```
> 
> No IP address for `example.com`?
> 
> Same response with `sdns://AgEAAAAAAAAAAKA-GhoPbFPz6XpJLVcIS1uYBwWe4FerFQWHb9g_2j24OCAyhv9lpl-vMghe6hOIw3OLp-N4c8kGzOPEootMwqWJiBJlYS1kbnMucnVieWZpc2guY24KL2Rucy1xdWVyeQ`.

Actually their server isn't very stable. About `example.com`, maybe their blocked it?

**Comment by jedisct1** [comment]
Blocking `example.com` is a little bit... surprising :)

I don't know what the best thing to do would be here. It doesn't seem to be reliable enough for daily usage :(

**Comment by qyb** [comment]
I'll remove example.com restriction from configuration later. Bandwidth is very expensive in china, this free service cannot afford more than 30MBytes

**Comment by jedisct1** [comment]
Still returning 503 errors :(
