### ISSUE TITLE
Has google DNS changed hash again?

### ISSUE THREAD

**Issue by csousougen** [DNSCrypt/dnscrypt-resolvers#485]
I'm getting 
[ERROR] Certificate hash [76802447a019931a3f004304c53fdc6c1b2c378dc4be8f73b39fd9c969dfb445] not found for [g
oogle]

**Comment by jedisct1** [comment]
Looks like they only deployed it in some regions.

That has was added, thanks to both of you for reporting this!

Can you confirm that it works after an update? (I still only get the previous one)

**Comment by syphyr** [comment]
I just removed public-resolvers.md and corresponding minisig and let it update again.. Then I restarted dnscrypt-proxy and I still see the error.
May 12 02:12:54 droid dnscrypt-proxy[8756]: [2021-05-12 02:12:54] [CRITICAL] [google] Certificate hash [76802447a019931a3f004304c53fdc6c1b2c378dc4be8f73b39fd9c969dfb445] not found

**Comment by syphyr** [comment]
Sorry, I thought I had the new changes, but I did not.

**Comment by csousougen** [comment]
It works! You have to update the public-resolvers.md file first. 
Thank you!
