### ISSUE TITLE
nextdns hash issue

### ISSUE THREAD

**Issue by mikeS7** [DNSCrypt/dnscrypt-resolvers#486]
I've got
`[2021-05-12 13:59:23] [ERROR] Certificate hash [3286ff65a65faf32085eea1388c3738ba7e37873c906cce3c4a28b4cc2a58988] not found for [nextdns]`

_dnscrypt-proxy -show-certs_ returns for nextdns and nextdns-ipv6
`[2021-05-12 13:56:59] [NOTICE] Advertised cert: [CN=nextdns.io] [e200a1dda665b2463d90182ac70d25c8775a6f025fc6c9e95b83d33cded60107]`
`[2021-05-12 13:56:59] [NOTICE] Advertised cert: [CN=R3,O=Let's Encrypt,C=US] [444ebd67bb83f8807b3921e938ac9178b882bd50aadb11231f044cf5f08df7ce]`
`[2021-05-12 13:56:59] [NOTICE] Advertised cert: [CN=ISRG Root X1,O=Internet Security Research Group,C=US] [11b102e6b1f63e528984d6025f32b138241fc88bbd7519574d70c9832d53e1e8]`
`[2021-05-12 13:56:59] [NOTICE] Advertised cert: [CN=nextdns.io] [e200a1dda665b2463d90182ac70d25c8775a6f025fc6c9e95b83d33cded60107]`
`[2021-05-12 13:56:59] [NOTICE] Advertised cert: [CN=R3,O=Let's Encrypt,C=US] [444ebd67bb83f8807b3921e938ac9178b882bd50aadb11231f044cf5f08df7ce]`
`[2021-05-12 13:56:59] [NOTICE] Advertised cert: [CN=ISRG Root X1,O=Internet Security Research Group,C=US] [11b102e6b1f63e528984d6025f32b138241fc88bbd7519574d70c9832d53e1e8]`

looks like an issue with  [CN=R3,O=Let's Encrypt,C=US]  hash

**Comment by jedisct1** [comment]
Let's Encrypt rolled new certificates.

All the DoH resolvers using it have been updated to include the new certificates.
