### ISSUE TITLE
Add ControlD

### ISSUE THREAD

**Issue by yegors** [DNSCrypt/dnscrypt-resolvers#488]
Hi there,

ControlD is a fully customizable DNS service that allows you to not only block annoyances like malware, tracking, ads or IoT telemetry, but also unblock over 150 services through a network of servers in over 100 cities. 

Although to get access to full feature set you need a paying plan, we have completely free community resolvers that block various types of content including malware (domain level, and IP level), ads and trackers, social networks and a completely unfiltered DNS resolver: https://controld.com/#free-dns

```
Unfiltered Resolver:
--------
DoH: https://freedns.controld.com/p0
DoT: p0.freedns.controld.com
Legacy: 76.76.2.0
sdns://AgcAAAAAAAAACjc2Ljc2LjIuMTEAFGZyZWVkbnMuY29udHJvbGQuY29tAy9wMA

Blocks Malware (based on hostnames and resolved IP addresses):
--------
DoH: https://freedns.controld.com/p1
DoT: p1.freedns.controld.com
Legacy: 76.76.2.1
sdns://AgcAAAAAAAAACjc2Ljc2LjIuMTEAFGZyZWVkbnMuY29udHJvbGQuY29tAy9wMQ

Blocks Malware + Trackers + Ads: 
--------
DoH: https://freedns.controld.com/p2
DoT: p2.freedns.controld.com
Legacy: 76.76.2.2
sdns://AgcAAAAAAAAACjc2Ljc2LjIuMTEAFGZyZWVkbnMuY29udHJvbGQuY29tAy9wMg

Blocks Malware, Ads, and Social networks:
--------
DoH: https://freedns.controld.com/p3
DoT: p3.freedns.controld.com
Legacy: 76.76.2.3
sdns://AgcAAAAAAAAACjc2Ljc2LjIuMTEAFGZyZWVkbnMuY29udHJvbGQuY29tAy9wMw
```

Thanks!

**Comment by jedisct1** [comment]
Hi!

Would you mind submitting a pull request for this?

Like other resolvers, each entry should have a name and a description. Filtering resolvers should also have the "no filter" flag unset. Certificate hashes are also missing (should probably be `4fcc406b51cee0544e516ce74b53b5484f7371f2be5b18e463b30faa6a285971` in your case).

**Comment by yegors** [comment]
How does one compute this hash with openssl? Can you point me in the right direction, if possible? 

I'm getting a totally different hash

```
openssl asn1parse -in cert.pem -out /dev/stdout -noout -strparse 4 | openssl dgst -sha256
(stdin)= fe5943c9e8af5c15ef5d2c7cb49ac7678ce3bd87cff195a3b60ddb2d6659d893
```

Where cert.pem is the certificate from `openssl s_client -connect freedns.controld.com:443`

**Comment by jedisct1** [comment]
`dnscrypt-proxy -show-certs` prints it for you.

Also see:
- [operational recommendations for DoH server operators](https://github.com/jedisct1/doh-server#operational-recommendations)
- [DNS stamps and certificate hashes](https://github.com/jedisct1/doh-server#dns-stamp-and-certificate-hashes)
