### ISSUE TITLE
ssl.gstatic.com returns a Google China address via v.dnscrypt.uk 

### ISSUE THREAD

**Issue by adrianlzt** [DNSCrypt/dnscrypt-resolvers#495]
dnscrypt.uk server resolves ssl.gstatic.com with a chinese inaccessible IP (at least from Spain):
```
➜ dnslookup ssl.gstatic.com  sdns://AQcAAAAAAAAADzEwNC4yMzguMTg2LjE5MiDtST2M6teQZk8GPEe3lZojaS18kDY8nkPMtZF75bQe5R0yLmRuc2NyeXB0LWNlcnQudi5kbnNjcnlwdC51aw
...
;; ANSWER SECTION:
ssl.gstatic.com.        857     IN      A       203.208.41.34
ssl.gstatic.com.        857     IN      A       203.208.41.34
```
```
➜ geoiplookup 203.208.41.34
GeoIP Country Edition: CN, China
```
```
➜ ping -c 2 203.208.41.34
PING 203.208.41.34 (203.208.41.34) 56(84) bytes of data.

--- 203.208.41.34 ping statistics ---
2 packets transmitted, 0 received, 100% packet loss, time 1014ms
```

Looks like that Gchat uses that address (https://ssl.gstatic.com/dynamite/images/cleardot.gif?zx=lvgz1mtwrunv) to check if the app is connected.

Using dnscrypt, when the cache is expired, some times dnscrypt.uk server is selected, resolves to that chinese IP and the gchat stop working.

@ianbashford any idea why your server is returning that strange IP?

**Comment by ericlagergren** [comment]
I've noticed similar problems for `dl.google.com` pulling in Chinese IP addresses.
