### ISSUE TITLE
why was anon-inconnu removed?

### ISSUE THREAD

**Issue by ericlagergren** [DNSCrypt/dnscrypt-resolvers#503]
Hi Frank, on 22 April my resolver anon-inconnu was removed. How come? The resolver still works and I plan on supporting it indefinitely. Could it be added back please?

**Comment by jedisct1** [comment]
Hi Eric,

And sorry for that :(

It has been added back.

The resolver worked perfectly, but the relay didn't respond any longer.

While all servers and relays are constantly tested, both manually and via the CI, there's currently no automated way to check when a resolver or relay comes back online after an outage. This is definitely something to improve.

**Comment by ericlagergren** [comment]
No worries. Thank you for adding it back!
