### ISSUE TITLE
odoh-crypto-sx does not have an ODoH configuration

### ISSUE THREAD

**Issue by syphyr** [DNSCrypt/dnscrypt-resolvers#510]
When testing odoh-crypto-sx, I get the following startup error:

Jun  7 23:56:47 droid dnscrypt-proxy[877]: [2021-06-07 23:56:47] [NOTICE] dnscrypt-proxy 2.0.46-beta1
Jun  7 23:56:47 droid dnscrypt-proxy[877]: [2021-06-07 23:56:47] [NOTICE] Network connectivity detected
Jun  7 23:56:47 droid dnscrypt-proxy[877]: [2021-06-07 23:56:47] [NOTICE] Using systemd sockets
Jun  7 23:56:47 droid dnscrypt-proxy[877]: [2021-06-07 23:56:47] [NOTICE] Wiring systemd TCP socket #0, dnscrypt-proxy.socket, 127.0.0.1:5454
Jun  7 23:56:47 droid dnscrypt-proxy[877]: [2021-06-07 23:56:47] [NOTICE] Wiring systemd UDP socket #1, dnscrypt-proxy.socket, 127.0.0.1:5454
Jun  7 23:56:47 droid dnscrypt-proxy[877]: [2021-06-07 23:56:47] [NOTICE] Wiring systemd TCP socket #2, dnscrypt-proxy.socket, [::1]:5454
Jun  7 23:56:47 droid dnscrypt-proxy[877]: [2021-06-07 23:56:47] [NOTICE] Wiring systemd UDP socket #3, dnscrypt-proxy.socket, [::1]:5454
Jun  7 23:56:47 droid dnscrypt-proxy[877]: [2021-06-07 23:56:47] [NOTICE] Source [relays] loaded
Jun  7 23:56:47 droid dnscrypt-proxy[877]: [2021-06-07 23:56:47] [NOTICE] Source [odoh] loaded
Jun  7 23:56:47 droid dnscrypt-proxy[877]: [2021-06-07 23:56:47] [NOTICE] Source [public-resolvers] loaded
Jun  7 23:56:47 droid dnscrypt-proxy[877]: [2021-06-07 23:56:47] [NOTICE] Loading the set of allowed names from [allowed-names]
Jun  7 23:56:47 droid dnscrypt-proxy[877]: [2021-06-07 23:56:47] [NOTICE] Firefox workaround initialized
Jun  7 23:56:47 droid dnscrypt-proxy[877]: [2021-06-07 23:56:47] [NOTICE] Loading the set of blocking rules from [blocked-names]
Jun  7 23:56:49 droid dnscrypt-proxy[877]: [2021-06-07 23:56:49] [ERROR] [odoh-crypto-sx] does not have an ODoH configuration
Jun  7 23:56:49 droid dnscrypt-proxy[877]: [2021-06-07 23:56:49] [NOTICE] dnscrypt-proxy is waiting for at least one server to be reachable

**Comment by jedisct1** [comment]
What relay are you using for it?

**Comment by jedisct1** [comment]
Also, can you run a `-short-certs` to check that you don't get a different cert than I do for the relay?

**Comment by syphyr** [comment]
I'm not using it as a relay. I thought this was a server.  When I use -show-certs, this is the results:

[2021-06-08 00:26:54] [NOTICE] dnscrypt-proxy 2.0.46-beta1
[2021-06-08 00:26:54] [NOTICE] Source [public-resolvers] loaded
[2021-06-08 00:26:54] [NOTICE] Source [relays] loaded
[2021-06-08 00:26:54] [NOTICE] Source [odoh] loaded
[2021-06-08 00:26:54] [NOTICE] Loading the set of allowed names from [allowed-names]
[2021-06-08 00:26:54] [NOTICE] Firefox workaround initialized
[2021-06-08 00:26:54] [NOTICE] Loading the set of blocking rules from [blocked-names]

**Comment by syphyr** [comment]
I am testing it like this:
server_names = ['odoh-crypto-sx']

**Comment by jedisct1** [comment]
ODoH servers should be used via ODoH relays.

**Comment by syphyr** [comment]
odoh-cloudflare works fine without a relay defined.

**Comment by jedisct1** [comment]
Note to self: output a hard error when an ODoH server is configured without a relay.

I thought it would be a useful feature for debugging your own ODoH server, but this is going to be a support hell.

**Comment by syphyr** [comment]
odoh-crypto-sx is still not working, even with a relay configured.  Although, odoh-cloudflare is working with relay now as well.
