### ISSUE TITLE
censurfridns / uncensoreddns

### ISSUE THREAD

**Issue by livingentity** [DNSCrypt/dnscrypt-resolvers#513]
Hi!
I saw that after all this time the following DoH servers (non-logging, no filter, DNSSEC) are still missing from DNSCrypt:
```
https://anycast.uncensoreddns.org/dns-query
https://unicast.uncensoreddns.org/dns-query
```

Further information: https://blog.uncensoreddns.org/dns-servers/

Please add them.

**Comment by jedisct1** [comment]
Can you submit a proper pull request (for the `v3/public-resolvers.md` file)?

Thank you!
