### ISSUE TITLE
Repo to register complaints with Jit DNS?

### ISSUE THREAD

**Issue by jenabaivab** [DNSCrypt/dnscrypt-resolvers#516]
Hello there,

I have been testing @coolquasar 's dns resolver located in India, but unfortunately there have been a few false positives in my limited usage with the DNS service. 

Is there any specific repository where i can open issues for false positives regarding the particular resolver?

Sorry if this is the wrong place to ask this, but I didn't know where else to go, considering this repo is where I found the DNS entry in the first place

**Comment by jedisct1** [comment]
Since you mentioned @coolquasar , he should see this issue :)

**Comment by jedisct1** [comment]
Has the issue been resolved?

@coolquasar

**Comment by coolquasar** [comment]
@jedisct1 Nope Frank, haven't been active lately. 

@jenabaivab Please provide a list of false positives, I will be happy to fix them for you. I apologize for late response, I haven't been active lately. You could reach me on reddit as well, same handle. GitHub and reddit are equal channels to reach me. Thanks!

**Comment by jenabaivab** [comment]
> Please provide a list of false positives, I will be happy to fix them for you. I apologize for late response, I haven't been active lately. You could reach me on reddit as well, same handle. GitHub and reddit are equal channels to reach me. Thanks!

@coolquasar Actually github has no means of communication without a specific repo and issues channel. It would be helpful if you could either open a repo for dns service false positives, or maybe allow reporting issues on the existing repositories. 
I have a few false positives to report, will contact you with the necessary details.
