### ISSUE TITLE
Signature problem with v2/public-resolvers.md

### ISSUE THREAD

**Issue by davidemyers** [DNSCrypt/dnscrypt-resolvers#519]
`dnscrypt-proxy` 2.0.31 that ships with Ubuntu 20.04 is failing to start with the latest update to `v2/public-resolvers.md` with the message:
```
Unable to retrieve source [public-resolvers]: [Invalid signature]
```
Signature verification fails at the command line (tested on macOS Big Sur with `minisign` from Homebrew):
```
$ minisign -Vm public-resolvers.md -P RWQf6LRCGA9i53mlYecO4IzT51TGPpvWucNSCh1CBM0QTaLn73Y7GFO3
Signature verification failed
```
The previous version of `public-resolvers.md` (taken from `/tmp` on a running system) checks out OK:
```
$ minisign -Vm public-resolvers.md -P RWQf6LRCGA9i53mlYecO4IzT51TGPpvWucNSCh1CBM0QTaLn73Y7GFO3
Signature and comment signature verified
Trusted comment: timestamp:1624278493	file:public-resolvers.md
```

**Comment by jedisct1** [comment]
This has been fixed since, and signature verification is now constantly monitored.

Thanks!

**Comment by jedisct1** [comment]
Recent versions of `dnscrypt-proxy` are not affected: whenever for whatever reason, a list cannot be used, the previous one keeps being used until a valid list can be downloaded again.

Unfortunately, distributions always ship with outdated software.
