### ISSUE TITLE
DNS.SB (DoH)

### ISSUE THREAD

**Issue by Showfom** [DNSCrypt/dnscrypt-resolvers#520]
Hello,

We have updated our infrastructure for DNS.SB DoH servers

https://dns.sb/doh/

Here is the DoH servers list currently use

|   Location	            |   DoH URL                          	|   Hosting Provider	|
|-----------------------	|-----------------------------------	|-------------------	|
|   Global CDN     |   `https://doh.dns.sb/dns-query`  	|  xTom   	        |
|   Anycast CDN    |   `https://doh.sb/dns-query`  	|  xTom  	        |
|   Düsseldorf, Germany     |   `https://de-dus.doh.sb/dns-query`  	|   xTom   	        |
|   Frankfurt, Germany	    |   `https://de-fra.doh.sb/dns-query`	    |   xTom    	        |
|   Amsterdam, Netherlands	|   `https://nl-ams.doh.sb/dns-query`	    |   xTom   	        |
|   Amsterdam, Netherlands  |   `https://nl-ams2.doh.sb/dns-query`    |   xTom   	        |
|   London, United Kingdom  |   `https://uk-lon.doh.sb/dns-query`     |   xTom   	        |
|   Tallinn, Estonia        |   `https://ee-tll.doh.sb/dns-query`     |   xTom   	        |
|   Osaka, Japan            |   `https://jp-kix.doh.sb/dns-query`     |   xTom  	        |
|   Hong Kong, China        |   `https://hk-hkg.doh.sb/dns-query`     |   xTom   	        |
|   Sydney, Australia       |   `https://au-syd.doh.sb/dns-query`     |   xTom   	        |
|   Chicago, United States  |   `https://us-chi.doh.sb/dns-query`     |   HostVenom       	|
|   Bengaluru, India        |   `https://in-blr.doh.sb/dns-query`     |   DigitalOcean       	|
|   Singapore               |   `https://sg-sin.doh.sb/dns-query`     |   Linode    	        |
|   Seoul, South Korea      |   `https://kr-sel.doh.sb/dns-query`     |   Amazon AWS      	|
|   Moscow, Russia          |   `https://ru-mow.doh.sb/dns-query`     |   Servers.com       	|

**Comment by jedisct1** [comment]
Hi!

Would it be possible to send a pull request to add/update these new entries?

Thank you!
