### ISSUE TITLE
How to update

### ISSUE THREAD

**Issue by telehost** [DNSCrypt/dnscrypt-resolvers#521]
How to update? i.e. 62.112.140.149

**Comment by jedisct1** [comment]
Can you clarify what you want to do?

What would you like to update?

What is this IP address?

**Comment by telehost** [comment]
I want to add my own resolvers instead of using predefinied servers. Is this possible? Thanks.

**Comment by jedisct1** [comment]
Is your question related to dnscrypt-proxy? Or some other software? Or are you asking how to change DNS settings in your operating system (which one)?
