### ISSUE TITLE
No client version 1 servers anymore?

### ISSUE THREAD

**Issue by hkmaly** [DNSCrypt/dnscrypt-resolvers#525]
Do I understand correctly that despite the 155 lines in v1/dnscrypt-resolvers.csv there is only SINGLE server on IPv4 actually supporting protocol version 1, and that one is logging AND filtering stuff not suitable for children? (I suppose that means anything related to privacy ... children should learn they are not going to have any).

**Comment by jedisct1** [comment]
Clients that only support version 1 of the protocol don't exist any more. It was not specified and was just for early testing.

The last `dnscrypt-proxy` version that implemented it was released 8 years ago, other clients never implemented it.

You may be confusing the protocol and `dnscrypt-proxy`. These are different things, with their own versions. `dnscrypt-proxy v1` had support for DNSCrypt v2 for a long time.
