### ISSUE TITLE
Zackptg5-us-pit server back up

### ISSUE THREAD

**Issue by Zackptg5** [DNSCrypt/dnscrypt-resolvers#526]
I need to watch this thing more carefully, ~~looked like watchtower botched it up somehow.~~  Think I got it fixed so that won't happen next time

- If servers go down in the future, would you be able to tag me or whoever's server it is so we have a chance to fix it next time (or if you know of a good way of monitoring it)? 

Edit: figured out what happened. I put the wrong port number in when updating docker stuff so it got silently blocked by ufw :sweat_smile:

**Comment by jedisct1** [comment]
Hi Zack,

Proper monitoring and automatically notifying operators is definitely something I need to work on.

Meanwhile, https://download.dnscrypt.info/dnscrypt-resolvers/status/ is constantly updated with the status of resolvers and relays.

You can use a service such as https://uptimerobot.com to monitor that page for the string `FAIL: <resolver name>` or the absence of `pass: <resolver name>`. Granted, that's a little bit hacky, but it works :)

**Comment by Zackptg5** [comment]
I'll look into doing that, thanks! Think you forgot to revert commit d03f57daf24e66d4dd2276d0afd2b7743a6d5ebb

**Comment by jedisct1** [comment]
> I'll look into doing that, thanks! Think you forgot to revert commit [d03f57d](https://github.com/DNSCrypt/dnscrypt-resolvers/commit/d03f57daf24e66d4dd2276d0afd2b7743a6d5ebb)

Indeed!

Done!

**Comment by Zackptg5** [comment]
Great! Got the uptimerobot going for all my sites/servers now, super helpful, thanks!
