### ISSUE TITLE
Whitespace in public resolver IDs

### ISSUE THREAD

**Issue by taam** [DNSCrypt/dnscrypt-resolvers#542]
The new servers `kenshiro ipv6` and `suami ipv6` have a space in their ID. The current IDs are already not quite consistent, but this adds a new element. I don't know if this might cause technical problems, this is just supposed to be a note regarding consistency, given that there are lots of entries with `-ipv6`.

**Comment by jedisct1** [comment]
Nod.

@lucenera Would you be fine renaming these?

**Comment by lucenera** [comment]
Sure. I couldn't attend the live. I hope it's still all on Youtube. Congratulations on everything.

**Comment by jedisct1** [comment]
Thank you!
