### ISSUE TITLE
Please add my DoH Servers in China

### ISSUE THREAD

**Issue by qyb** [DNSCrypt/dnscrypt-resolvers#55]
ea-dns.rubyfish.cn and uw-dns.rubyfish.cn

## ea-dns.rubyfish.cn
resolve posioning domain from East-Asia upstream
'sdns://AgQAAAAAAAAADzExNS4xNTkuMTU0LjIyNgAPZG5zLnJ1YnlmaXNoLmNuCi9kbnMtcXVlcnk'

## uw-dns.rubyfish.cn
resolve posioning domain from US-West upstream
'sdns://AgQAAAAAAAAADDQ3Ljk5LjE2NS4zMQAPZG5zLnJ1YnlmaXNoLmNuCi9kbnMtcXVlcnk'

**Comment by jedisct1** [comment]
Done!

Thank you so much for running these!
