### ISSUE TITLE
DoH endpoint location in compiled .json document.

### ISSUE THREAD

**Issue by martinheidegger** [DNSCrypt/dnscrypt-resolvers#560]
Some of the DoH endpoints in this useful project have different https endpoints for `DoH` for different purposes.
For example: [libredns](https://libredns.gr/) currently specifies on their documentation page the regular endpoint as

`https://doh.libredns.gr/dns-query`

and the ads-free endpoint as

`https://doh.libredns.gr/ads`

In the listing of doh entries however, there is no distinction between [regular](https://github.com/DNSCrypt/dnscrypt-resolvers/blob/01da5b15ec579d92dd40a16008c7405763e48f51/v3/public-resolvers.md#libredns) and [without ads](https://github.com/DNSCrypt/dnscrypt-resolvers/blob/01da5b15ec579d92dd40a16008c7405763e48f51/v3/public-resolvers.md#libredns-noads).

Would it be a good idea to add this optional field somehow to the dataset?

**Comment by jedisct1** [comment]
If two URLs behave differently, they should be listed as different entries. If only because the attributes will be different (an ad-blocking server cannot have the "no filter" attribute).

The path or even the protocol don't really matter.

**Comment by martinheidegger** [comment]
The [list of resolves](https://download.dnscrypt.info/resolvers-list/json/public-resolvers.json) contains both `libredns-noads` and `libredns` as two different entries, but without looking at the documentation. How to get the correct `https` endpoint for `libredns-noads`?

**Comment by jedisct1** [comment]
I'm not sure I follow. These entries have a different description and different stamps.

**Comment by martinheidegger** [comment]
Indeed they do, but in order to use the `DoH` servers, one needs to look at the libredns website and look up the https endpoints for either, doesn't it make sense in a computer readable list to also includ the https endpoints for each?

**Comment by jedisct1** [comment]
I'm still a little bit confused :)

The file you linked is just used to display the map of the dnscrypt.info website.

The actual resolvers lists are the `.md` files available in this repository and on the mirrors. They include a description for each resolver, and are well-structured to be computer readable.

**Comment by martinheidegger** [comment]
Maybe you can help me find a better description for this issue? Given the structured data in the `.md`, I don't see a way how to get to the `DoH` endpoint for `libredns-noads`. I opened this issue to add the necessary data to the `.md` file (and `.json` respectively) to be able to directly get the endpoint necessary for `libredns-noads`.

But maybe I am missing something? Is there currently a programatic way to get `https://doh.libredns.gr/ads` for `libredns-noads` without looking up the information on the libredns homepage?

**Comment by jedisct1** [comment]
The information to connect is in the stamp. For DoH, this includes the properties, but also the host/SNI name, the path, the IP addresses, bootstrap resolvers and certificate hashes.

**Comment by rampageX** [comment]
@martinheidegger 

is this clear for you?

![sdns](https://user-images.githubusercontent.com/994081/132330067-34e46905-6946-4c45-97c5-6f4e3bc1028b.png)

**Comment by martinheidegger** [comment]
@rampageX @jedisct1 Thank you for the clarification, I was indeed confused by this, as it was not visible in the compiled `.json` file. As such I changed the title slightly and am wondering if the path attribute can be extracted into the compiled `.json` file, without the need to additionally parse the stamp?

**Comment by jedisct1** [comment]
I'd recommend parsing the stamp, as it includes the required information for certificate verification, which a URL alone doesn't have.

**Comment by martinheidegger** [comment]
There are several libraries out there that do not (yet?) support certificate verification in dns packets making it a bit tough to implement 😅 . 

But what seems more relevant is that DoH settings are usually done using an endpoint URL. As I understand it, users of DoH settings, don't expect the dns to be invalidated if the DNSSEC certificate changes. Isn't that what the https part is for?

**Comment by jedisct1** [comment]
See the [operational recommendations](https://github.com/dnSCrypt/doh-server#operational-recommendations) for the DoH server.

`https` only verifies a host name, not its ownership.

As a practical example, after the DNSCrypt project moved from the `dnscrypt.org` to the `dnscrypt.info` domain, the former was taken over by a marketing/SEO spam company that set up a fake version of the original website. Any binary downloaded from the old location can now potentially include malware. Signature verification prevents this. For DoH, cert verification ensures that the data comes from the expected owner.
