### ISSUE TITLE
CORS support

### ISSUE THREAD

**Issue by martinheidegger** [DNSCrypt/dnscrypt-resolvers#561]
When accessing a DoH server through a browser environment, it is important to know whether or not an endpoint supports CORS. It seems like this _should_ be possible to be gathered while testing endpoints?! Would it be a good idea to gather this data automatically and add it to the list?

**Comment by jedisct1** [comment]
Just curious: what is a use case for sending DNS queries from a web browser? I wasn't able to find any.

**Comment by martinheidegger** [comment]
The use case for this is to show on a website if the dns configuration for a webpage matches a standard. Standard in question: dnslink.dev

**Comment by jedisct1** [comment]
That information can be added to the description. But I'm not sure that a lot of servers support that. `doh-server` certainly didn't. Until today :)

What DNS packet parsing/building library are you using in Javascript? Or are you using WebAssembly for this?

**Comment by martinheidegger** [comment]
I wrote my own library for doh parsing: https://github.com/martinheidegger/dns-query it should be quite fast. I currently have my own [list of dns servers](https://github.com/martinheidegger/dns-query/blob/main/endpoints.md) that I want to replace with this list, quite a few servers do come with CORS support.
