### ISSUE TITLE
powerdns-doh - gone for now

### ISSUE THREAD

**Issue by DummyPayload** [DNSCrypt/dnscrypt-resolvers#572]
As stated on their webpage DNS is no longer available. I experienced it also due to it being my dns of a choice.
Statement : https://powerdns.org/
![image](https://user-images.githubusercontent.com/30219562/134826589-709c9799-e672-4596-89b6-f90402d6b0e0.png)

**Comment by jedisct1** [comment]
Removed, thanks!
