### ISSUE TITLE
AhaDNS.com NEW DoH servers and NEW ControlD DoH server provider.

### ISSUE THREAD

**Issue by Jefe777** [DNSCrypt/dnscrypt-resolvers#601]
# AhaDNS.com
You can please add the **NEW DoH servers**:
- [DNS over HTTPS (DoH) – AhaDNS.com](https://ahadns.com/dns-over-https/)
- [DNS Stamps – AhaDNS.com](https://ahadns.com/dns-stamps/)

**Chicago** (DoH)
- IPv4: 193.29.62.196
- IPv6: 2605:4840:3:c4::c4
- Host name: `doh.chi.ahadns.net`

**New York** (DoH)
- IPv4: 185.213.26.187
- IPv6: 2a0d:5600:33:3::3
- Host name: `doh.ny.ahadns.net`

#
# ControlD - Control Your Internet
You can also add to this **NEW DoH server provider**:
- [ControlD - Free DNS](https://controld.com/free-dns/)
- [Generate DNS Stamp | ControlD KB](https://kb.controld.com/en/tutorials/dns-stamp)

## Free resolver servers:
**Unfiltered** (DoH)
- IPv4: 76.76.2.11
- Host name: `freedns.controld.com/p0`
-  Information: No DNS record blocking or manipulation

**Malware** (DoH)
- IPv4: 76.76.2.11
- Host name: `freedns.controld.com/p1`
-  Information: Block Malware

**Ads & Tracking** (DoH)
- IPv4: 76.76.2.11
- Host name: `freedns.controld.com/p2`
-  Information: Block Malware + Ads

**Social** (DoH)
- IPv4: 76.76.2.11
- Host name: `freedns.controld.com/p3`
-  Information: Block Malware + Ads + Social

**Family Friendly** (DoH)
- IPv4: 76.76.2.11
- Host name: `freedns.controld.com/family`
-  Information: Block Malware + Ads + Adult Content + Drugs

**Uncensored** (DoH)
- IPv4: 76.76.2.11
- Host name: `freedns.controld.com/uncensored`
-  Information: Unblock Censored Domains from various countries

#

Thanks.

**Comment by jedisct1** [comment]
Hi!

Can you send a pull request (changing `v3/public-resolvers.md`) for these changes?

Thanks!

**Comment by Jefe777** [comment]
@jedisct1 I do not know how to do it.

**Comment by jedisct1** [comment]
Browse the [resolvers list](https://github.com/DNSCrypt/dnscrypt-resolvers/blob/master/v3/public-resolvers.md) and hit the `.` key.

**Comment by Jefe777** [comment]
II do not understand what you say.

I just want someone who has the knowledge (that I don't have), **please** add those DoH servers.

**Comment by PeterDaveHello** [comment]
PR #606 sent for AhaDNS New York node, if everything goes as expect, some other PRs will also be sent later.

**Comment by Last-times** [comment]
@jedisct1 @PeterDaveHello 

Thank you very much for your help, but **ControlD** DNS Stamps are wrong, the name and stamp are not correct and here is the **AhaDNS.com** server in **Chicago** to add it:

# ControlD server Fixed:

Unfiltered (DoH): [Path = /**p0**]
* `sdns://AgMAAAAAAAAACjc2Ljc2LjIuMTEAFGZyZWVkbnMuY29udHJvbGQuY29tAy9wMA`

⠀
Malware (DoH): [Path = /**p1**]
* `sdns://AgMAAAAAAAAACjc2Ljc2LjIuMTEAFGZyZWVkbnMuY29udHJvbGQuY29tAy9wMQ
`

⠀
Ads & Tracking (DoH): [Path = /**p2**]
* `sdns://AgMAAAAAAAAACjc2Ljc2LjIuMTEAFGZyZWVkbnMuY29udHJvbGQuY29tAy9wMg
`

⠀
Social (DoH): [Path = /**p3**]
* `sdns://AgMAAAAAAAAACjc2Ljc2LjIuMTEAFGZyZWVkbnMuY29udHJvbGQuY29tAy9wMw
`

⠀
Family Friendly (DoH): [Path = /**family**]
* `sdns://AgMAAAAAAAAACjc2Ljc2LjIuMTEAFGZyZWVkbnMuY29udHJvbGQuY29tBy9mYW1pbHk
`

⠀
Uncensored (DoH): [Path = /**uncensored**]
* `sdns://AgMAAAAAAAAACjc2Ljc2LjIuMTEAFGZyZWVkbnMuY29udHJvbGQuY29tCy91bmNlbnNvcmVk
`

# AhaDNS.com **Chicago** server:

IPv4
`sdns://AgMAAAAAAAAADTE5My4yOS42Mi4xOTagzBBg05yDKbYrb7x9DW35MJhpuYHn5jktXNj6QI9NgOYgRE69Z7uD-IB7OSHpOKyReLiCvVCq2xEjHwRM9fCN984SZG9oLmNoaS5haGFkbnMubmV0Ci9kbnMtcXVlcnk
`

IPv6
`sdns://AgMAAAAAAAAAFFsyNjA1OjQ4NDA6MzpjNDo6YzRdoMwQYNOcgym2K2-8fQ1t-TCYabmB5-Y5LVzY-kCPTYDmIEROvWe7g_iAezkh6TiskXi4gr1QqtsRIx8ETPXwjffOEmRvaC5jaGkuYWhhZG5zLm5ldAovZG5zLXF1ZXJ5
`

**I hope you guys fix those bugs and thank you very much.**

**Comment by Jefe777** [comment]
@jedisct1 @PeterDaveHello 

Thank you very much for your help, but **ControlD** DNS Stamps are wrong, the name and stamp are not correct and here is the missing **AhaDNS.com** server in **Chicago** to add it:

# ControlD server Fixed:

**Unfiltered** (DoH): [Path = /**p0**]
* `sdns://AgMAAAAAAAAACjc2Ljc2LjIuMTEAFGZyZWVkbnMuY29udHJvbGQuY29tAy9wMA`

⠀

**Malware** (DoH): [Path = /**p1**]
* `sdns://AgMAAAAAAAAACjc2Ljc2LjIuMTEAFGZyZWVkbnMuY29udHJvbGQuY29tAy9wMQ
`

⠀

**Ads & Tracking** (DoH): [Path = /**p2**]
* `sdns://AgMAAAAAAAAACjc2Ljc2LjIuMTEAFGZyZWVkbnMuY29udHJvbGQuY29tAy9wMg
`

⠀

**Social** (DoH): [Path = /**p3**]
* `sdns://AgMAAAAAAAAACjc2Ljc2LjIuMTEAFGZyZWVkbnMuY29udHJvbGQuY29tAy9wMw
`

⠀

**Family Friendly** (DoH): [Path = /**family**]
* `sdns://AgMAAAAAAAAACjc2Ljc2LjIuMTEAFGZyZWVkbnMuY29udHJvbGQuY29tBy9mYW1pbHk
`

⠀

**Uncensored** (DoH): [Path = /**uncensored**]
* `sdns://AgMAAAAAAAAACjc2Ljc2LjIuMTEAFGZyZWVkbnMuY29udHJvbGQuY29tCy91bmNlbnNvcmVk
`

# AhaDNS.com **Chicago** server:

IPv4
`sdns://AgMAAAAAAAAADTE5My4yOS42Mi4xOTagzBBg05yDKbYrb7x9DW35MJhpuYHn5jktXNj6QI9NgOYgRE69Z7uD-IB7OSHpOKyReLiCvVCq2xEjHwRM9fCN984SZG9oLmNoaS5haGFkbnMubmV0Ci9kbnMtcXVlcnk
`

IPv6
`sdns://AgMAAAAAAAAAFFsyNjA1OjQ4NDA6MzpjNDo6YzRdoMwQYNOcgym2K2-8fQ1t-TCYabmB5-Y5LVzY-kCPTYDmIEROvWe7g_iAezkh6TiskXi4gr1QqtsRIx8ETPXwjffOEmRvaC5jaGkuYWhhZG5zLm5ldAovZG5zLXF1ZXJ5
`

**I hope you guys fix those bugs and thank you very much.**

**Comment by Jefe777** [comment]
#609

**Comment by Jefe777** [comment]
Thanks.
