### ISSUE TITLE
Use a more maintainable and human readable format to maintain the public resolvers?

### ISSUE THREAD

**Issue by PeterDaveHello** [DNSCrypt/dnscrypt-resolvers#613]
Currently, we uses the dns stamps in the public resolver files, however, it's pretty hard to validate the cert, hostname, DNSSEC, filter from the stamps, as the v1, v2 files are generated automatically, it'll be great that we can have another human readable and more maintainable public resolvers file to be edit, and automatically generate the `v3/public-resolvers.md ` just like the other  public resolvers files.

**Comment by jedisct1** [comment]
A VSCode Extension to edit stamps would be nice :)

**Comment by PeterDaveHello** [comment]
@jedisct1 why not simply edit the raw data, just convert it to the stamp after?
