### ISSUE TITLE
mullvad resolvers do not work because they lack IP addresses.

### ISSUE THREAD

**Issue by crocket** [DNSCrypt/dnscrypt-resolvers#635]
I thought DoH resolvers without IP addresses were going to use bootstrap resolvers, but they didn't.

I had to manually add IP addresses to resolver stamps by using https://dnscrypt.info/stamps/

**Comment by crocket** [comment]
Are you sure this is completed? mullvad DoH servers still don't have IP addresses.

**Comment by jedisct1** [comment]
IP addresses can be added, but it is not going to solve the actual issue, which seems to only happen on your environment.

Are the bootstrap resolvers reachable? Do you get an answer for `doh.mullvad.net` when querying them directly.

**Comment by crocket** [comment]
I tested again, and the issue seems fixed. I don't understand.
