### ISSUE TITLE
Add nextdns ultralow server

### ISSUE THREAD

**Issue by bigdargon** [DNSCrypt/dnscrypt-resolvers#638]
Ultralow servers are servers located in each country, making domain name resolution faster. I am living in Vietnam, when using the ultralow server, there are 2 following servers.

```
; <<>> DiG 9.11.3-1ubuntu1.16-Ubuntu <<>> dns.nextdns.io @8.8.8.8
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 34850
;; flags: qr rd ra; QUERY: 1, ANSWER: 3, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;dns.nextdns.io.			IN	A

;; ANSWER SECTION:
dns.nextdns.io.		300	IN	CNAME	steering.nextdns.io.
steering.nextdns.io.	60	IN	A	203.162.172.59
steering.nextdns.io.	60	IN	A	103.199.17.192

;; Query time: 281 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Tue Feb 15 09:46:08 +07 2022
;; MSG SIZE  rcvd: 98
```

Ultralow server does not use anycast address like `45.90.28.0` `45.90.30.0` `2a07:a8c0::` `2a07:a8c1::`

In addition to the available nextdns resolution servers (with IP address attached). I request to add `nextdns-ultralow` server without ip address, then `dns.nextdns.io` domain name will switch to bootstrap resolver (ex 8.8.8.8) server to get server ip address.

I have DNS Stramps calculated according to the parameters
- IP Address: (blank)
- Host name: `dns.nextdns.io`
- Hashes: (blank)
- Path: `/`

```
sdns://AgcAAAAAAAAAAAAOZG5zLm5leHRkbnMuaW8BLw
```

Thanks!

**Comment by jedisct1** [comment]
Hi!

And thanks!

What should be the description for this entry? Is the main difference that the server location depends on the bootstrap resolver rather than automatic routing?

**Comment by bigdargon** [comment]
The ultra low server feature is currently not officially announced on the homepage, but i can find is a map of the network pops of nextdns.

![Screenshot 2022-02-16 at 09-39-47 NextDNS](https://user-images.githubusercontent.com/10969626/154186016-55b7de9c-bdeb-4b3f-8c07-1e591acc93cd.png)

This is a thread I created before https://help.nextdns.io/t/y4ht599/servers-in-vietnam-are-testing

And here is the latest diagnostic (a network diagnostic tool by nextdns https://github.com/nextdns/diag) I created https://nextdns.io/diag/93eb6770-8ed1-11ec-9013-af4fb4bae918

In the diagnostic there are 2 groups of servers, `Ultra Low Latency` and `Anycast`. `Ultra Low Latency` servers are only available when using encrypted DNS like DoH, DoT (no anycast IP address attached). The `Anycast` servers use the anycast IP address, which is for plain-text DNS without encryption.

If you attach the IP address to the DoH, you will still use the Anycast server. If the domain `dns.nextdns.io` is resolved at bootstrap servers (with ECS) like Google DNS or OpenDNS (Cloudflare DNS is sometimes available) there will be an IP address in the country in which the user lives.

Ex:

```
; <<>> DiG 9.11.3-1ubuntu1.16-Ubuntu <<>> dns.nextdns.io @8.8.8.8
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 37255
;; flags: qr rd ra; QUERY: 1, ANSWER: 3, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;dns.nextdns.io.			IN	A

;; ANSWER SECTION:
dns.nextdns.io.		300	IN	CNAME	steering.nextdns.io.
steering.nextdns.io.	60	IN	A	103.199.17.192
steering.nextdns.io.	60	IN	A	203.162.172.59

;; Query time: 298 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Wed Feb 16 09:59:47 +07 2022
;; MSG SIZE  rcvd: 98
```

```
; <<>> DiG 9.11.3-1ubuntu1.16-Ubuntu <<>> dns.nextdns.io @208.67.222.222
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 57309
;; flags: qr rd ra; QUERY: 1, ANSWER: 3, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;dns.nextdns.io.			IN	A

;; ANSWER SECTION:
dns.nextdns.io.		298	IN	CNAME	steering.nextdns.io.
steering.nextdns.io.	60	IN	A	203.162.172.59
steering.nextdns.io.	60	IN	A	103.199.17.192

;; Query time: 337 msec
;; SERVER: 208.67.222.222#53(208.67.222.222)
;; WHEN: Wed Feb 16 10:03:44 +07 2022
;; MSG SIZE  rcvd: 98
```

```
; <<>> DiG 9.11.3-1ubuntu1.16-Ubuntu <<>> dns.nextdns.io @1.1.1.1
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 57523
;; flags: qr rd ra; QUERY: 1, ANSWER: 3, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;dns.nextdns.io.			IN	A

;; ANSWER SECTION:
dns.nextdns.io.		300	IN	CNAME	steering.nextdns.io.
steering.nextdns.io.	60	IN	A	103.199.17.192
steering.nextdns.io.	60	IN	A	203.162.172.59

;; Query time: 290 msec
;; SERVER: 1.1.1.1#53(1.1.1.1)
;; WHEN: Wed Feb 16 09:59:52 +07 2022
;; MSG SIZE  rcvd: 98
```

But if using 9.9.9.9 (without ECS) and 9.9.9.11 (with ECS), the ultra low server will be different

```
; <<>> DiG 9.11.3-1ubuntu1.16-Ubuntu <<>> dns.nextdns.io @9.9.9.9
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 4888
;; flags: qr rd ra; QUERY: 1, ANSWER: 3, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;dns.nextdns.io.			IN	A

;; ANSWER SECTION:
dns.nextdns.io.		289	IN	CNAME	steering.nextdns.io.
steering.nextdns.io.	49	IN	A	103.62.48.147
steering.nextdns.io.	49	IN	A	217.146.9.93

;; Query time: 62 msec
;; SERVER: 9.9.9.9#53(9.9.9.9)
;; WHEN: Wed Feb 16 10:04:37 +07 2022
;; MSG SIZE  rcvd: 98
```

```
; <<>> DiG 9.11.3-1ubuntu1.16-Ubuntu <<>> dns.nextdns.io @9.9.9.11
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 11996
;; flags: qr rd ra; QUERY: 1, ANSWER: 3, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
; COOKIE: 8003ee986a373c0a90e09d04620c6a125d10079ace398b8d (good)
;; QUESTION SECTION:
;dns.nextdns.io.			IN	A

;; ANSWER SECTION:
dns.nextdns.io.		300	IN	CNAME	steering.nextdns.io.
steering.nextdns.io.	60	IN	A	203.162.172.59
steering.nextdns.io.	60	IN	A	103.199.17.192

;; Query time: 305 msec
;; SERVER: 9.9.9.11#53(9.9.9.11)
;; WHEN: Wed Feb 16 10:05:54 +07 2022
```

**Comment by bigdargon** [comment]
@jedisct1 I have updated and checked it seems that the DNS Stamp of `nextdns` and `nextdns-ultralow` are the same. And nextdns-ultralow has been assigned an IP address? So, the incoming server is still anycast, not ultralow (I tried it on raspberry and the result is at https://test.nextdns.io it still shows anycast as true)

As far as I know, dnscrypt-proxy will connect to hostname using the IP address available in DNS Stamp. And I want to add `-ultralow` by not putting IP address in DNS Stamp, then dnscrypt-proxy will resolve hostsname via bootstrap server.

Please check this out! Thank you!
