### ISSUE TITLE
How to check anon relays?

### ISSUE THREAD

**Issue by PwOSS** [DNSCrypt/dnscrypt-resolvers#647]
Hey

I saw that you classified pwoss as down a2b0138. I did not realize that it is down and now I'm curious how to check.

I would also like to automate the tests myself, like https://github.com/DNSCrypt/dnscrypt-resolvers/blob/master/.github/workflows/resolverscheck.sh.

**Comment by jedisct1** [comment]
This is the script I use: https://gist.github.com/6d95552d70db1bfabd5c15fad48590f1

`DNSCRYPT_PROXY` has to be set to the actual path to `dnscrypt-proxy`.

**Comment by jedisct1** [comment]
Servers and relays are also continuously monitored here: https://download.dnscrypt.info/status/
