### ISSUE TITLE
Cloudflare Support

### ISSUE THREAD

**Issue by OdinVex** [DNSCrypt/dnscrypt-resolvers#654]
I understand that some old, decrepit routers still use 1.1.1.1. Should we be held back by them? Perhaps a legacy-configuration for such installations would be better?

**Comment by jedisct1** [comment]
Can you clarify the issue you are reporting?

Cloudflare is present in the lists (`cloudflare`, `cloudflare-family`, `cloudflare-family-ipv6`, `cloudflare-ipv6`, `cloudflare-security`, `cloudflare-security-ipv6`, `onion-cloudflare`, `odoh-cloudflare`).

**Comment by OdinVex** [comment]
> Can you clarify the issue you are reporting?
> 
> Cloudflare is present in the lists (`cloudflare`, `cloudflare-family`, `cloudflare-family-ipv6`, `cloudflare-ipv6`, `cloudflare-security`, `cloudflare-security-ipv6`, `onion-cloudflare`, `odoh-cloudflare`).

I've been trying to get DD-WRT to work with Cloudflare's DoT, but the entries for Cloudflare aren't there. I searched the DD-WRT repository and couldn't find any references for Cloudflare. Furthermore, I tried searching in the Issues section here and noticed a lot of posts about it conflicting with ancient routers that use 1.1.1.1 for private DNS and figured to ask. I never saw any Issue updated to reflect the change in the sentiment I kept seeing. ^_^

**Comment by jedisct1** [comment]
This repository is a public list of DNSCrypt, DoH, ODOH resolvers and relays.

It has nothing to do with DD-WRT. I'd suggest asking for help on the DD-WRT forum regarding how to setup DNS on this system.

**Comment by OdinVex** [comment]
> This repository is a public list of DNSCrypt, DoH, ODOH resolvers and relays.
> 
> It has nothing to do with DD-WRT. I'd suggest asking for help on the DD-WRT forum regarding how to setup DNS on this system.

I already knew it had nothing to do with DD-WRT, I figured I'd check the source of their project to determine where they got their lists and saw it wasn't in there, I figured I'd suggest it here if it was missing and based on Issues, it was. Anyway...
