### ISSUE TITLE
European DNS resolvers dnscrypt v2 up to date 22 12 2018

### ISSUE THREAD

**Issue by absynteZero** [DNSCrypt/dnscrypt-resolvers#67]
[dnscrypt v2 - DNSSec No log - European servers.txt](https://github.com/DNSCrypt/dnscrypt-resolvers/files/2705508/dnscrypt.v2.-.DNSSec.No.log.-.European.servers.txt)
Hi

This is an European dns resolvers list, dnscrypt v2 , DNSSec and no log.

>>>> .toml , conf file

Up to date 22 12 2018

aZ

**Comment by jedisct1** [comment]
Thank you.

**Comment by publicarray** [comment]
@absynteZero you may want to add it to the wiki here: https://github.com/jedisct1/dnscrypt-proxy/wiki/DNS-server-sources
