### ISSUE TITLE
id-gmail dnscryptv2

### ISSUE THREAD

**Issue by pengelana** [DNSCrypt/dnscrypt-resolvers#68]
This is a DNS server provided by id-gmail, located in Singapore.

It filters out ads, tracker and malware. It doesn’t log anything. It supports DNSSEC.

sdns://AQMAAAAAAAAADTE0OS4yOC4xNTIuODEg75aAZujZlPBl2D7d0xru7fVthldGPkrKR83X_pfD1PYcMi5kbnNjcnlwdC1jZXJ0LmRucy50aWFyLmFwcA

**Comment by jedisct1** [comment]
...and you're in!

Thanks for running this resolver!

**Comment by pengelana** [comment]
DNS-over-HTTPS, provided by id-gmail, located in Singapore. Filter out ad/ad-tracking and malware. supports DNSSEC and no logs.

sdns://AgMAAAAAAAAACzQ1LjMyLjEwNS40AAxkb2gudGlhci5hcHAKL2Rucy1xdWVyeQ

thanks.
