### ISSUE TITLE
[Request] VietDNS server from Vietnam

### ISSUE THREAD

**Issue by bigdargon** [DNSCrypt/dnscrypt-resolvers#686]
VietDNS server has just been configured in Vietnam (Ho Chi Minh City).
- The server has no filtering, ad filtering and search filtering
- Using Bind9 as the recursive DNS server
- And support DNSSEC

Here are the server details:
- DNS server does not filter
```
103.151.57.57 (Primary DNS)
103.151.56.56

DoH: https://ns.vietdns.vn
```

- DNS servers filter ads, malware, phishing
```
103.151.57.2 (Primary DNS)
103.151.56.2

DoH: https://dns.vietdns.vn
```

- DNS servers block ads, malware, phishing, block adult content and enable safe search
```
103.151.57.23 (Primary DNS)
103.151.56.24

DoH: https://kids.vietdns.vn
```

Homepage: https://vietdns.vn/

More info: https://voz.vn/t/update-dns-viet-phien-ban-voz-chan-quang-cao-virut-noi-dung-doc-hai.553969/

**Comment by tranhoangcore** [comment]
Added new pull request #708 
@bigdargon

**Comment by tranhoangcore** [comment]
Hi @bigdargon, Please contact the administrator of vietdns about the domain `ns.vietdns.vn`, which has the wrong certificate ssl.

**Comment by jedisct1** [comment]
In addition to actually testing these entries, adding the certificates hashes is also highly recommended for security.

**Comment by bigdargon** [comment]
@tranhoangcore reported. Thanks!

**Comment by bigdargon** [comment]
@tranhoangcore fixed https://voz.vn/t/vietdns-dns-viet-phien-ban-voz-chan-quang-cao-virut-noi-dung-doc-hai.553969/post-19041506

**Comment by tranhoangcore** [comment]
Hi @bigdargon Updated.

**Comment by tranhoangcore** [comment]
@bigdargon Can you contact the admin to allow github IP range exceptions?
cc @jedisct1 
https://github.com/DNSCrypt/dnscrypt-resolvers/pull/708#issuecomment-1188947253

**Comment by bigdargon** [comment]
I contacted the admin at the voz forum!  I will close this issue to move to PR.  Thanks for creating PR!

**Comment by tranhoangcore** [comment]
@bigdargon Any updates? :)

**Comment by bigdargon** [comment]
@tranhoangcore You can follow this https://voz.vn/t/vietdns-dns-viet-phien-ban-voz-chan-quang-cao-virut-noi-dung-doc-hai.553969/
