### ISSUE TITLE
[Edit] NextDNS anycast domain name and server address

### ISSUE THREAD

**Issue by bigdargon** [DNSCrypt/dnscrypt-resolvers#687]
I have looked at the public DNS server information, it seems that the NextDNS server is a bit confused

- NextDNS (IPv4), domain name `anycsast.dns.nextdns.io` & server address `95.179.134.211`
![Screenshot 2022-06-08 094430](https://user-images.githubusercontent.com/10969626/172520418-44626919-0a56-4621-a808-328bc6500a5e.png)

I suggest to edit the domain name from `anycsast.dns.nextdns.io` to `dns.nextdns.io` (or `anycast.dns.nextdns.io`), address `95.179.134.211` to anycast address `45.90.28.0`

- NextDNS (IPv6), domain name `anycsast.dns.nextdns.io`
![Screenshot 2022-06-08 094946](https://user-images.githubusercontent.com/10969626/172521202-59d18873-8cc5-46ad-a322-bc5b38fcaa57.png)

I suggest to edit the domain name from `anycsast.dns.nextdns.io` to `dns.nextdns.io` (or `anycast.dns.nextdns.io`)

Thanks!

**Comment by jedisct1** [comment]
Looks like there was indeed a typo. Thank you!
