### ISSUE TITLE
id-gmail DNS-over-HTTPS

### ISSUE THREAD

**Issue by pengelana** [DNSCrypt/dnscrypt-resolvers#69]
DNS-over-HTTPS, provided by id-gmail, located in Singapore. Filter out ad/ad-tracking and malware. supports DNSSEC and no logs.

sdns://AgMAAAAAAAAACzQ1LjMyLjEwNS40AAxkb2gudGlhci5hcHAKL2Rucy1xdWVyeQ

Thanks.

**Comment by jedisct1** [comment]
Added! Thank you!
