### ISSUE TITLE
Incorrect stamps

### ISSUE THREAD

**Issue by Heptazhou** [DNSCrypt/dnscrypt-resolvers#706]
@jedisct1 Hi!

just found that some stamps are lying (came from #692 and #696)

[public-resolvers.md](https://github.com/fransallen/dnscrypt-resolvers/blob/master/v3/public-resolvers.md?plain=1)-[L2197-L2214](https://github.com/fransallen/dnscrypt-resolvers/blob/82771b9647c5cef2ec18eed3d0e9e57af9aa920b/v3/public-resolvers.md?plain=1#L2197-L2214):

> Blocks malware, adware, gambling, fakenews, and adult sites. Google, Bing,
> and YouTube are set to Safe mode.

> sdns://AgcAAAAAAAAADTEwOC4xMzcuNDQuMzOgzBBg05yDKbYrb7x9DW35MJhpuYHn5jktXNj6QI9NgOYgRE69Z7uD-IB7OSHpOKyReLiCvVCq2xEjHwRM9fCN984SZmFtaWx5LnB1cmVkbnMub3JnCi9kbnMtcXVlcnk

> sdns://AgcAAAAAAAAAKFsyNDA2OmRhMTk6NjZmOmU4MTA6NjNmYzo0MTczOjFjMDg6YTAwZF2gzBBg05yDKbYrb7x9DW35MJhpuYHn5jktXNj6QI9NgOYgRE69Z7uD-IB7OSHpOKyReLiCvVCq2xEjHwRM9fCN984SZmFtaWx5LnB1cmVkbnMub3JnCi9kbnMtcXVlcnk

obviously the stamps should **not** be `nofilter: true`

```json5
{ name: "puredns-family-doh", proto: "DoH", ipv6: false, addrs: ["family.puredns.org", "146.190.6.140"], ports: [443], dnssec: true, nolog: true, nofilter: true, description: "Public DNS resolver for Families in Indonesia - https://puredns.org/family/\nBlocks malware, adware, gambling, fakenews, and adult sites. Google, Bing,\nand YouTube are set to Safe mode.", stamp: "sdns://AgcAAAAAAAAADTEwOC4xMzcuNDQuMzOgzBBg05yDKbYrb7x9DW35MJhpuYHn5jktXNj6QI9NgOYgRE69Z7uD-IB7OSHpOKyReLiCvVCq2xEjHwRM9fCN984SZmFtaWx5LnB1cmVkbnMub3JnCi9kbnMtcXVlcnk" }
{ name: "puredns-family-doh-ipv6", proto: "DoH", ipv6: true, addrs: ["family.puredns.org", "[2400:6180:0:d0::16a2:d001]"], ports: [443], dnssec: true, nolog: true, nofilter: true, description: "Public DNS resolver for Families in Indonesia - https://puredns.org/family/\nBlocks malware, adware, gambling, fakenews, and adult sites. Google, Bing,\nand YouTube are set to Safe mode.", stamp: "sdns://AgcAAAAAAAAAKFsyNDA2OmRhMTk6NjZmOmU4MTA6NjNmYzo0MTczOjFjMDg6YTAwZF2gzBBg05yDKbYrb7x9DW35MJhpuYHn5jktXNj6QI9NgOYgRE69Z7uD-IB7OSHpOKyReLiCvVCq2xEjHwRM9fCN984SZmFtaWx5LnB1cmVkbnMub3JnCi9kbnMtcXVlcnk" }
```

**Comment by jedisct1** [comment]
Good catch, thank you so much!

The stamps have been fixed.

Thanks!
