### ISSUE TITLE
Human readable versions?

### ISSUE THREAD

**Issue by BrianG61UK** [DNSCrypt/dnscrypt-resolvers#721]
Are these lists available anywhere in a more human-readable format (not as DNS stamps)?

**Comment by hyder365** [comment]
A long time ago they were in a convenient csv format with the name, location, IP, etc. Now they're obfuscated with this sdns:// stuff. I really don't like it.

**Comment by jedisct1** [comment]
A long time ago the only encrypted DNS protocol was DNSCrypt. Now there's a new one every year.

`dnscrypt-proxy -list-all -json` dumps the resolvers list as JSON.

In the [resolvers list](https://dnscrypt.info/public-servers) you can also simply click the name of a resolver to see the technical details.
But this info is really only useful to software. The rest is in the description itself.

**Comment by BrianG61UK** [comment]
@nadeem49 Thank you very much indeed.
