### ISSUE TITLE
Malformed Response on all relays since 22/09/16 5pm CEST

### ISSUE THREAD

**Issue by logopk** [DNSCrypt/dnscrypt-resolvers#737]
Hi, I'm facing a problem with resolution.

[2022-09-17 14:00:18] [ERROR] No valid network configuration for [odoh-cloudflare]
[2022-09-17 14:00:18] [NOTICE] dnscrypt-proxy is waiting for at least one server to be reachable
[2022-09-17 14:00:28] [NOTICE] Anonymizing queries for [odoh-crypto-sx] via [odohrelay-crypto-sx]
[2022-09-17 14:00:29] [WARNING] Unable to decrypt response from [odoh-crypto-sx]: [Malformed response]
[2022-09-17 14:00:29] [INFO] Trying to fetch the [odoh-crypto-sx] configuration again
[2022-09-17 14:00:29] [NOTICE] Anonymizing queries for [odoh-crypto-sx] via [odohrelay-crypto-sx]
[2022-09-17 14:00:31] [WARNING] Unable to decrypt response from [odoh-crypto-sx]: [Malformed response]

All of a sudden I had no DNS anymore. Fortunately I was able to connect my pihole to cloudflared (config from some time ago)

I have no idea how to troubleshoot. What info do you need - or maybe you immediately know the problem?! log_level does not get more output.

I can tell from the mtail logs (and my prometheus exporter) that it started with a NETWORK_ERROR and since then I get only NOT_READY response codes.
 
Thanks in advance

Peter

**Comment by ecliptik** [comment]
I had the same issue with the `odohrelay-crypto-sx` relay.

Switching to a different relay[1] and resolver[2] resolved the issue. I don't understand why `odohrelay-crypto-sx` suddenly started giving `[Malformed response]` message though.

1. https://raw.githubusercontent.com/DNSCrypt/dnscrypt-resolvers/master/v3/odoh-relays.md
2. https://raw.githubusercontent.com/DNSCrypt/dnscrypt-resolvers/master/v3/odoh-servers.md

**Comment by logopk** [comment]
How can I force dnscrypt-proxy to use another relay - the file is loaded from github and odohrelay-crypto-sx is #1...

**Comment by logopk** [comment]
> How can I force dnscrypt-proxy to use another relay - the file is loaded from github and odohrelay-crypto-sx is #1...

routes = [
    { server_name='*', via=['odohrelay-crypto-sx', ''] }
]
????

**Comment by logopk** [comment]
`routes = [ { server_name='*', via=['odohrelay-ibksturm', ''] } ]` did the trick.

Is there a way to get this resolved automagically? Just in case ibksturm fails one day?

**Comment by ibksturm** [comment]
try this


routes = [ { server_name='*', via=['odohrelay-ibksturm', 'server2,‘server3‘] } ]

**Comment by jedisct1** [comment]
This is due to a [regression in zig](https://github.com/ziglang/zig/issues/12880) when using the stage2 compiler.

A new version of the `odoh-crypto-sx` code compiled with the previous (stage1) compiler has been deployed, and the relay should be up and running again.

Thanks!
