### ISSUE TITLE
mullvad-doh Certificate hash not found

### ISSUE THREAD

**Issue by julianfairfax** [DNSCrypt/dnscrypt-resolvers#745]
```
dnscrypt-proxy[527599]: [2022-10-29 21:51:36] [NOTICE] dnscrypt-proxy 2.1.2
dnscrypt-proxy[527599]: [2022-10-29 21:51:36] [NOTICE] Network connectivity detected
dnscrypt-proxy[527599]: [2022-10-29 21:51:36] [NOTICE] Now listening to 127.0.0.1:53 [UDP]
dnscrypt-proxy[527599]: [2022-10-29 21:51:36] [NOTICE] Now listening to 127.0.0.1:53 [TCP]
dnscrypt-proxy[527599]: [2022-10-29 21:51:36] [NOTICE] Source [public-resolvers] loaded
dnscrypt-proxy[527599]: [2022-10-29 21:51:36] [NOTICE] Source [relays] loaded
dnscrypt-proxy[527599]: [2022-10-29 21:51:36] [NOTICE] Firefox workaround initialized
dnscrypt-proxy[527599]: [2022-10-29 21:51:36] [CRITICAL] [mullvad-doh] Certificate hash [11b102e6b1f63e528984d6025f32b138241fc88bbd7519574d70c9832d53e1e8] not found
dnscrypt-proxy[527599]: [2022-10-29 21:51:36] [ERROR] Certificate hash not found
dnscrypt-proxy[527599]: [2022-10-29 21:51:36] [NOTICE] dnscrypt-proxy is waiting for at least one server to be reachable
```

**Comment by jedisct1** [comment]
Is your cache file up to date?

Entries for mullvad have been updated a week ago.

**Comment by jedisct1** [comment]
Did you change something, like the default list of ciphers?

**Comment by jedisct1** [comment]
Weird. What does `dnscrypt-proxy -show-certs` print?

**Comment by jedisct1** [comment]
That's impossible :)

**Comment by jedisct1** [comment]
Your config file was probably changed to redirect the service logs somewhere else. Can you look there, or disable it? (Look for `log_file` and `use_syslog` in the configuration file).

**Comment by jedisct1** [comment]
Can you revert to the default settings so that `dnscrypt-proxy` prints something?

**Comment by jedisct1** [comment]
Try to find where the logs are (apparently either in `/var/log/dnscrypt-proxy/dnscrypt-proxy.log` or in the system log).

What hashes are being logged there?

**Comment by v1gnesh** [comment]
Isn't it because the IP address isn't there?
That is, if we're pointing to a DNS server, isn't it best if it's an IP address?
If not, what's going to resolve the hostname of the DNS server itself?

[This mullvad blog post](https://mullvad.net/en/help/dns-over-https-and-dns-over-tls/) says:

**Without ad blocking**

doh.mullvad.net has address 194.242.2.2
doh.mullvad.net has IPv6 address 2a07:e340::2

**With ad blocking**

adblock.doh.mullvad.net has address 194.242.2.3
adblock.doh.mullvad.net has IPv6 address 2a07:e340::3

Can the IP addresses be hardcoded in `public-resolvers.md`?
The IP doesn't change that often; I'm sure someone will create an issue or PR here in case an update is needed.

**Comment by v1gnesh** [comment]
Ah my mistake. DNS stamp holds this info.
Based on https://dnscrypt.info/stamps/, it appears that the stamp in `public-resolvers.md` for mullvad is just for the IPv6 address. I have IPv6 turned off. Have you too, @julianfairfax ?

**Comment by v1gnesh** [comment]
Put the IP address you want in the DNS stamp calculator, and use the generated `sdns://`.
That means having your own version of `public-resolvers.md`.
So it's best to just wait for this repo's maintainers to help update the main file, to make the `sdns://` hold both the IP address and the hostname... for both regular and adblocking mullvad endpoints.

**Comment by jedisct1** [comment]
Are we talking about `mullvad-doh`?


The stamp is:

`sdns://AgcAAAAAAAAAACARsQLmsfY-UomE1gJfMrE4JB_Ii711GVdNcMmDLVPh6A9kb2gubXVsbHZhZC5uZXQKL2Rucy1xdWVyeQ`

There are no IP addresses here.

Having the logs you get when starting the server would really help.

**Comment by v1gnesh** [comment]
@jedisct1, Yes I can see that in the public resolvers file.
Putting the stamp at https://dnscrypt.info/stamps doesn't show an IP address.
So can the stamp be composed from IP address info too?

**Comment by jedisct1** [comment]
Now, what does `dnscrypt-proxy -show-certs` show?

**Comment by jedisct1** [comment]
In the previous message, you somehow managed to get the logs from the server.

What are these, with `-show-certs`?

**Comment by jedisct1** [comment]
This is the information that was needed since the beginning :)

They switched to a new Godaddy certificate.

Fixed. Just refresh your cache :)

**Comment by v1gnesh** [comment]
> This is the information that was needed since the beginning :)
> 
> They switched to a new Godaddy certificate.
> 
> Fixed. Just refresh your cache :)

Thank you! So IP is not involved/required at all in the user config..

**Comment by v1gnesh** [comment]
@jedisct1 ...?
