### ISSUE TITLE
PureDNS is back online

### ISSUE THREAD

**Issue by MF-Debug** [DNSCrypt/dnscrypt-resolvers#746]
Can you please add it back? Thanks.

**Comment by jedisct1** [comment]
Would it be an option to allow GitHub CI and the `dnscrypt.info` server to access it?

**Comment by MF-Debug** [comment]
> Would it be an option to allow GitHub CI and the `dnscrypt.info` server to access it?

not sure about this solution :(

**Comment by jedisct1** [comment]
Could you possibly reach out to the PureDNS maintainers about this?

**Comment by MF-Debug** [comment]
not sure about that. I can tag him here in this issue & hope he sees this.
@fransallen Can you help with the issue please?
