### ISSUE TITLE
Failed to receive successful response from [odoh-koki-ams]

### ISSUE THREAD

**Issue by pannal** [DNSCrypt/dnscrypt-resolvers#751]
Hey,

I can see regular failures in the log, which always are:
```
 [2022-11-02 00:35:56] [WARNING] Failed to receive successful response from [odoh-koki-ams]
```

The config for `odoh-koki-ams` is:
```
{ server_name='odoh-koki-ams', via=['odohrelay-crypto-sx', 'odohrelay-surf'] },
```

**Comment by jedisct1** [comment]
Unfortunately, ODoH is generally slow and unreliable.

**Comment by pannal** [comment]
Oh, so should it be avoided in general?

**Comment by jedisct1** [comment]
It's mostly there just for testing. The specification is not even finalized yet.

Also, it's slower than anonymized DNS and leaks your IP address, so, really it's only for testing.

**Comment by pannal** [comment]
Thanks. Weird that everyone seems to include those in their tutorials, then. I'll disable odoh for now.
