### ISSUE TITLE
IIJ DNS Resolver

### ISSUE THREAD

**Issue by sr093906** [DNSCrypt/dnscrypt-resolvers#763]
https://web.archive.org/web/20220924085342/https://public.dns.iij.jp/

According to the defunct page, the DNS server implements DNS blocking to prevent child pornography and record certain connection data though most of them are deleted after 24 hours, among other things worthy attention.

It is also a pilot project, similar to att's DoH service.

**Comment by jedisct1** [comment]
Thanks! The `no filter` flag has been removed.
