### ISSUE TITLE
mullvad-doh not working

### ISSUE THREAD

**Issue by MF-Debug** [DNSCrypt/dnscrypt-resolvers#765]
Mullvad has stopped working. Can you please remove it for the time being? Thanks.

**Comment by jedisct1** [comment]
Seems to be fine: https://download.dnscrypt.info/status/public-resolvers.txt

**Comment by jedisct1** [comment]
Yep, I tested them locally, no issues.

**Comment by jedisct1** [comment]
These stamps don't match the ones in the list https://github.com/DNSCrypt/dnscrypt-resolvers/blob/master/v3/public-resolvers.md#mullvad-adblock-doh
