### ISSUE TITLE
New resolver - zerologdns

### ISSUE THREAD

**Issue by libDarkstreet** [DNSCrypt/dnscrypt-resolvers#782]
Hi, my question is, is it possible to submit a new resolver?

We've been working on a project for a while now that is a bit different from the usual resolvers as it is also available from the Tor network. It's a completely private dns server that can be accessed from the clear internet too and supports DoH and DoT.

If I send the website and other informations, is there any chance it will be included?

**Comment by jedisct1** [comment]
Hi!

Of course you can!

Just fork this repository, add entries for your resolvers in the relevant files, and submit a pull request with the changes.

The files to update are:

- `v3/public-resolvers.md` for DNSCrypt and old school DoH servers
- `v3/odoh-servers.md` for Oblivious DoH servers.
- `v3/onion-services.md` for onion services (put the service name such as "jwioefhwuiuyfdrtedt4or.onion` in the `host name` field and leave the cert hashes empty)

If your servers can also anonymize client IP addresses, the relay names should be put in `v3/relays.md` (for anonymized DNSCrypt relays), or `v3/odoh-relays.md` (for ODoH relays).

Only files in `v3` need to be updated, the other ones will be automatically updated later.

**Comment by libDarkstreet** [comment]
Okay, thanks!

I've looked at the stamp calculator, but I don't fully understand how it works.

Can I specify multiple IPV4 and IPV6 addresses?  
What do I need to enter for the hash?

**Comment by jedisct1** [comment]
Hi!

Only one IP addresses can be included per stamp, but you can have multiple stamps for the same entry.

What software are you using? If you're using [DoH Server](https://github.com/dnscrypt/doh-server), the stamps (both for legacy DoH and ODoH) are printed on startup.

See [here](https://github.com/dnscrypt/doh-server#dns-stamp-and-certificate-hashes) for the hashes. If you're using Let's Encrypt, it's probably 444ebd67bb83f8807b3921e938ac9178b882bd50aadb11231f044cf5f08df7ce or cc1060d39c8329b62b6fbc7d0d6df9309869b981e7e6392d5cd8fa408f4d80e6 .

**Comment by libDarkstreet** [comment]
We use the DoH server made by [m13253](https://github.com/m13253/dns-over-https) with minor modifications for the json API. So it doesn't print the hashes. :(

ZeroSSL is used for the DoH service.
