### ISSUE TITLE
dnscrypt-proxy install issue

### ISSUE THREAD

**Issue by JiyeTang** [DNSCrypt/dnscrypt-resolvers#79]
Hi Guys,

When I was trying to install the dnscript-proxy on my device I encountered the following error:

./dnscrypt-proxy: symbol lookup error: ./dnscrypt-proxy: undefined symbol: crypto_core_hchacha20

I did some researches and someone says may be the version of libsodium is old; however, install the latest version did not fix my problem. 

Also when I performed:

./configure && make

I got an error like this:

configure: error: cannot find install-sh, install.sh, or shtool in libltdl/config "."/libltdl/config

does anyone have any suggestions?

**Comment by evilvibes** [comment]
Wrong place to ask. Ask here https://github.com/jedisct1/dnscrypt-proxy

**Comment by jedisct1** [comment]
Current versions do not use libsodium any more. You can also directly download precompiled binaries from the URL above.
