### ISSUE TITLE
Best testing method for resolvers

### ISSUE THREAD

**Issue by josephbu** [DNSCrypt/dnscrypt-resolvers#796]
Just a quick question regarding [commit](https://github.com/DNSCrypt/dnscrypt-resolvers/commit/e25e167351f961cab72398dfb38ae6d7aa9b1a08).

Are you able to share the best testing method so I can pick this up in the future? 

I'm not sure how 3 servers in different parts on the country on two different networks aren't reachable, certainly I'm still seeing plenty of traffic on IPv6 to them and also don't see connectivity issues from my VM at Hetzner FSN.

Either way, I'd like to make sure I'm testing correctly so I can identify this better :-)  Thanks in advance!

**Comment by jedisct1** [comment]
Hi!

Resolvers and relays are continuously monitored here: https://download.dnscrypt.info/resolvers-list/status/

So one thing you can do is set up an alert is your resolver name is not prefixed with `pass: ` on that page. https://uptimerobot.com is pretty cool for that kind of thing.

The tests are run from the OVH network.

Resolvers also get checked by GitHub CI, and from my connection via Free/Proxad.

Unfortunately, IPv6 connectivity tends to be unreliable. It's not uncommon to see hosts that are reachable from some networks and not others :(

**Comment by jedisct1** [comment]
Your resolvers look to be reachable now! So, the changes have been reverted.

I need to improve the checks to do it from multiple locations.

**Comment by josephbu** [comment]
@jedisct1 Thanks for the extra info I'll get a check going for (lack of) `pass:` on the status page so I can dig into it a bit if it happens again.

I run an [Uptime Kuma](https://github.com/louislam/uptime-kuma) instance at home and at Hetzer, Falkenstein, mostly works ok :-) 

Unfortunately [HetrixTools](https://hetrixtools.com/) who I use for external monitoring don't yet support IPv6 yet, so I'll setup an Uptime Robot check as well for backup.

Thanks for everything!
