### ISSUE TITLE
FDN DoT/DoH Servers

### ISSUE THREAD

**Issue by hucste** [DNSCrypt/dnscrypt-resolvers#807]
Since 04/19/2023, the FDN — French Data Network — an association to promote Open Internet and Usenet, published new DoT and DoH services! 
_(this is too an ISP)_

⇒ On port 853 for DoT:
IPv4 Adresses: 
- 80.67.169.12
- 80.67.169.40

IPv6 Adresses:
- 2001:910:800::12
- 2001:910:800::40

⇒ for DoH: 
- https://ns0.fdn.fr/dns-query
- https://ns1.fdn.fr/dns-query

See more informations (in French): https://www.fdn.fr/ouverture-des-services-dot-doh/

**Comment by jedisct1** [comment]
Do you mind submitting a pull request with a proper description and stamps?

**Comment by hucste** [comment]
I dont known how to do this!?

**Comment by hucste** [comment]
> Do you mind submitting a pull request with a proper description and stamps?

If you explain me where put the proper description and how to obtain stamps, it could certainly be possible ;)

**Comment by jedisct1** [comment]
The only files to update are:

`v3/public-resolvers.md`

and if your server also accepts ODoH, `v3/odoh-servers.md` as well.

Other versions of the list will be automatically updated from the `v3` one.

The DNS proxy should print the stamps when it starts, or somewhere in the log files.
If not, you can use the [online calculator](https://dnscrypt.info/stamps/)

Also see the [operational recommendations for DoH servers](https://github.com/dnscrypt/doh-server#operational-recommendations) and [how to get certificate hashes](https://github.com/dnscrypt/doh-server#dns-stamp-and-certificate-hashes).
