### ISSUE TITLE
odoh-relays.md - Most not working?

### ISSUE THREAD

**Issue by Sn0whax** [DNSCrypt/dnscrypt-resolvers#812]
It appears the following odoh relays are not working:
odohrelay-ams
odohrelay-se
odohrelay-surf
Only odohrelay-crypto-sx appears to work, can you confirm?

**Comment by jedisct1** [comment]
I'm gonna take a look as soon as possible.

**Comment by jedisct1** [comment]
`odohrelay-se` and `surf` are indeed not relaying ODoH any more.

They have been removed. And a new one (`marco.cx`) has been added.

I've verified that all the ODoH relays and servers are currently working.

Thanks again for the heads up!
