### ISSUE TITLE
Please add BebasDNS to the list

### ISSUE THREAD

**Issue by SlashyID** [DNSCrypt/dnscrypt-resolvers#819]
**BebasDNS** is popular public DNS resolver in Indonesia.

We already support DNSSEC, IPv6, and OpenNIC domain

We also didn't do logging

[Pull Request](https://github.com/DNSCrypt/dnscrypt-resolvers/pull/814)

I already did a pull request a long time ago, please review it thank you 🙏

**Comment by jedisct1** [comment]
Merged, thank you!

Does it also support ODoH?

**Comment by SlashyID** [comment]
Not yet but we plan to support more protocol in the future 🙏
