### ISSUE TITLE
[Request]  DoH3 / http3 Support

### ISSUE THREAD

**Issue by hbednar** [DNSCrypt/dnscrypt-resolvers#848]
Can you add support for DoH3 / http3 as it has improvements over DoH.

DNS with DoH3 Support:
h3://dns-unfiltered.adguard.com/dns-query
doh3.dns.nextdns.io
https://freedns.controld.com/p0

**Comment by jedisct1** [comment]
This is still DoH. There's no difference in the required parameters, regardless of the HTTP version. This doesn't affect the stamps.

The software should automatically use HTTP/3 if supported by the server. Just like in a web browser, URLs are still `https://`, not `http2` or `h3` or whatever.

**Comment by hbednar** [comment]
Maybe i didn't explain this very well but, like you said `if supported by the server` 
I would like the servers supporting http3 to be highlighted so, i can use servers with http3 support.
