### ISSUE TITLE
Some dnscry.pt servers are missing in the public-resolvers.md

### ISSUE THREAD

**Issue by Wabuo** [DNSCrypt/dnscrypt-resolvers#868]
For example, the Auckland one ..

@Brueggus is this somehow intended?
Also cheers for hosting the only relay in NZ

**Comment by jedisct1** [comment]
The list is synchronized with the `dnscrypt.pt` source manually. I should really look at automating this.

Is there a file that contains the relays? I randomly tried `https://www.dnscry.pt/relays.md` but there's nothing there.

**Comment by Wabuo** [comment]
Ther's is this 
https://github.com/DNSCrypt/dnscrypt-resolvers/blob/master/v3/relays.md

And this
https://www.dnscry.pt/anon-relays.md

Also go on to his side and scroll down a bit to see all the things he provides.
https://www.dnscry.pt

**Comment by Brueggus** [comment]
> @Brueggus is this somehow intended?

No, I am happy if those are added to the "offical" lists :)

There's also https://www.dnscry.pt/resolvers.json if that helps to keep the resolver lists in sync.

**Comment by jedisct1** [comment]
The relays have been added already. Thanks for the URL!
