### ISSUE TITLE
Anon relays not working

### ISSUE THREAD

**Issue by gombadi** [DNSCrypt/dnscrypt-resolvers#869]
Hi @jedisct1 

I noticed that a couple of my relays have been removed recently which is fine. If they are not working then they should be removed.

I know there is a page https://download.dnscrypt.info/resolvers-list/status/relays.txt which shows the results of the tests but was wondering if you can let me know how the testing is actually done?

I would not mind running the tests on my own servers if possible to quickly pick up on any issues. 

Overall it seems to be similar to a comment in an old issue about testing where some ipv6 addresses work from some networks but not others. 
I have been doing some digging and can see that ipv6 responses from some locations need the firewall opened to any high udp port but other locations do not. Would like to dig deeper and see if I can improve things. 

Gombadi

**Comment by jedisct1** [comment]
Here's the script I use. It's pretty ugly, but it does the job. https://gist.github.com/jedisct1/cc1b4aba0a2ae2e2bc3bf69debf7f99b
