### ISSUE TITLE
Not all servers labelled as supporting DNSSEC actually do

### ISSUE THREAD

**Issue by unbeatable-101** [DNSCrypt/dnscrypt-resolvers#872]
I have `require_dnsssec = true` set in my config and am only using dnscrypt servers from the default server list, yet when I use https://dnscheck.tools/ to check DNSSEC support, I'll sometimes get it saying DNSSEC is supported, and sometimes it will say it isn't. Here is an example of when it isn't.

<img width="1109" alt="Screenshot 2024-01-16 at 13 41 34" src="https://github.com/DNSCrypt/dnscrypt-resolvers/assets/58151048/2f95ebed-4038-4b3e-b34a-bbc8789dc1d5">

**Comment by jedisct1** [comment]
I can't read images, sorry.

DNSSEC support is reported by `dnscrypt-proxy -resolve`:

```text
$ dnscrypt-proxy -resolve example.com

./dnscrypt-proxy -resolve example.com
Resolving [example.com] using 127.0.0.1 port 53

Resolver      : 74.125.47.9
...
Name servers  : a.iana-servers.net., b.iana-servers.net.
DNSSEC signed : yes
```

What resolvers did you find not supporting DNSSEC while they had the DNSSEC bit set in their stamp?

**Comment by jedisct1** [comment]
It doesn't. Maybe we can use `-list -json` to get the DNSSEC information from the stamp, and indeed compare that to the output of `-resolve`.

**Comment by jedisct1** [comment]
Added this to my regular check scripts. And sure enough, it quickly detected quite a few resolvers that advertise DNSSEC but don't support it.

I'm going to add it to prcheck and to the status monitor.

**Comment by jedisct1** [comment]
> Probably I'm doing it wrong but both with https://dnscheck.tools/ ("Great! Your DNS responses are authenticated with DNSSEC") and using `dnscrypt-proxy -resolve example.com` ("DNSSES signed : yes") I get positive results for e.g. `UncensoredDNS`.

I just set `server_names = ['uncensoreddns-dk-ipv4']`, and ran `dnscrypt-proxy -resolve example.com`:

```text
Resolving [example.com] using 127.0.0.1 port 53

Resolver      : 89.233.43.71 (unicast.censurfridns.dk.)
Lying         : no
DNSSEC        : no, the resolver doesn't support DNSSEC
ECS           : ignored or selective
```

**Comment by jedisct1** [comment]
"DNSSEC signed" is printed in the section about the domain name you are querying, not the server properties.
