### ISSUE TITLE
Yandex stops supporting DNSCrypt

### ISSUE THREAD

**Issue by dartraiden** [DNSCrypt/dnscrypt-resolvers#873]
> Starting March 1, 2024, the DNSCrypt protocol will no longer be supported in Yandex DNS.

https://dns.yandex.com

**Comment by jedisct1** [comment]
Oh no, this is very sad news. But I guess they had no choice, Russia has their own CA so they can inspect TLS traffic at will, but not DNSCrypt.

**Comment by jedisct1** [comment]
Removed in d8cb91a1d6bd9e67c6b34b449cc8f41f0145f21e
