### ISSUE TITLE
dnscrypt.ca Removal

### ISSUE THREAD

**Issue by dnscrypt-ca** [DNSCrypt/dnscrypt-resolvers#881]
Please remove all eight entries in the public resolver list for dnscrypt.ca. My VPS provider is shutting down and the resolvers are expected to go down on February 24th. Announcement can be found in red at the top of the dnscrypt.ca home page.

**Comment by jedisct1** [comment]
Also I see you were still running `dnscrypt-wrapper` and the Go DoH server. For the same traffic, you may get away with a smaller instance just by upgrading the `encrypted-dns-server` and `doh-server`.

**Comment by woefulwabbit** [comment]
@dnscrypt-ca Perhaps you could try posting a request in the https://lowendtalk.com community, or looking at an existing offer like [this one](https://lowendtalk.com/discussion/193080/ssd-vps-available-in-13-locations-starting-at-2-4-mo-usa-canada-uk-germany/p1)
