### ISSUE TITLE
Key Rotation Procedure For dnsdist 

### ISSUE THREAD

**Issue by dnscrypt-ca** [DNSCrypt/dnscrypt-resolvers#884]
I have been doing some homework with hopes of getting dnscrypt.ca back on the public resolver list.  In my adventures, I have found that I kind of like PowerDNS/dnsdist but am struggling to automate DNSCrypt key rotation with it.  If anyone has had any luck with this I would greatly appreciate any tips.  I'm a little worried this may be seen as off-topic, but hopeful that if an elegant solution exists it will encourage the addition of more servers.

**Comment by jlongua** [comment]
I also struggled with DNSCrypt key rotation in dnsdist, but managed to come up with a workable solution. I maintain plan9dns, and all my configs are open sourced on github. https://github.com/jlongua/plan9-dns/blob/main/configs/dnsdist.conf .

**Comment by dnscrypt-ca** [comment]
Thanks a bunch @jlongua ... I admit I have gone back to playing with the wrapper in the meantime, but it is **great** to have a working example with dnsdist for everyone.  I'll close this issue, but hopefully if anyone else has any more they wish to add they'll still provide some feedback.  Much appreciated!
