### ISSUE TITLE
captnemo-in forwarding to Cisco

### ISSUE THREAD

**Issue by captn3m0** [DNSCrypt/dnscrypt-resolvers#9]
Trying to fix the comment in https://github.com/DNSCrypt/dnscrypt-resolvers/commit/8ce1a2a20e8201aadae055ed7d13fabd04a86d1b

>Warning: forwards queries to Cisco servers.

I tested my configuration (`dnscrypt-proxy 1.9.5` running locally with `ResolverName captnemo-in`) against https://www.dnsleaktest.com/results.html

The only server that shows up is `r5.compute.mum1.edc.strln.net` / `OpenDNS`.

The DNSCrypt-wrapper Exec is set as:

`ExecStart=/usr/local/sbin/dnscrypt-wrapper --resolver-address=208.67.222.222:53 --listen-address=10.47.0.5:4434 --provider-name=2.dnscrypt-cert.captnemo.in --crypt-secretkey-file=1.key --provider-cert-file=1.cert  --outgoing-address=10.47.0.5`

I'll a file a PR to remove the warning once this is confirmed as correct.

**Comment by jedisct1** [comment]
Your `dnscrypt-wrapper` command-line confirms that you are not using your own resolver but forwarding to Cisco :)

No problems with that, but this is worth mentioning as it may not match some people's privacy expectations.

**Comment by captn3m0** [comment]
Ahh, got it. Didn't know about the OpenDNS-Cisco relationship.

Is there any other upstream resolver that you might recommend? Don't want to run my own resolver (yet!)

**Comment by jedisct1** [comment]
The company was acquired in 2015 https://techcrunch.com/2015/06/30/cisco-to-buy-cloud-security-company-opendns-for-635m-in-cash/

If you don't want to run your own resolver, [Quad9](https://quad9.net/) (9.9.9.9) might be a better choice if only because it supports DNSSEC. Or you can join the [OpenNIC](https://www.opennic.org/) network.

**Comment by captn3m0** [comment]
THanks!
