### ISSUE TITLE
Interesting to see resolver inside China with possible government surveillance

### ISSUE THREAD

**Issue by Outofpit** [DNSCrypt/dnscrypt-resolvers#91]
Do you guys know what does this mean? 京ICP备18045418号-1京公网安备 11010802027577号

It might be OK you add the resolver here, but I'm going to warn people use dnscrypt inside China to watch out. Thanks.

**Comment by jedisct1** [comment]
What resolver were you using, what website did you try to access and where did you see this?

**Comment by Outofpit** [comment]
GeekDNS in eastern China (Shanghai).

GeekDNS is a non-logging public DNS service located in mainland china, that also blocks ads and trackers. Queries are cached locally, and, for some domains, resolved by servers located in Taiwan.

https://dns.233py.com/

sdns://AgMAAAAAAAAADTQ3LjEwMS4xMzYuMzcgPhoaD2xT8-l6SS1XCEtbmAcFnuBXqxUFh2_YP9o9uDgOZWRucy4yMzNweS5jb20KL2Rucy1xdWVyeQ


rubyfish-ea
Resolver in mainland China, forwarding queries for non-Chinese domains to upstream servers in East Asia.

https://www.rubyfish.cn/ sdns://AgUAAAAAAAAADzExNS4xNTkuMTU0LjIyNiA-GhoPbFPz6XpJLVcIS1uYBwWe4FerFQWHb9g_2j24OA9kbnMucnVieWZpc2guY24KL2Rucy1xdWVyeQ

And when you open either
https://dns.233py.com/
https://www.rubyfish.cn

You could find what I see.

**Comment by jedisct1** [comment]
This is the normal content.

What you see is the ICP license number. Websites in China have to be registered, and they must display that number to prove that they are legitimate.
