### ISSUE TITLE
uncensoreddns-dk-ipv4 unexpected EOF

### ISSUE THREAD

**Issue by ghost** [DNSCrypt/dnscrypt-resolvers#937]
`[uncensoreddns-dk-ipv4] [https://unicast.uncensoreddns.org/dns-query]: Post "https://unicast.uncensoreddns.org/dns-query?body_hash=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx": unexpected EOF`

Who needs to do what?

**Comment by jedisct1** [comment]
It's accessible over HTTP/2, but HTTP/3 is broken. 

The best thing to do would be to let them know: https://blog.uncensoreddns.org
