### ISSUE TITLE
dnsforge.de Servers

### ISSUE THREAD

**Issue by mauri5hut** [DNSCrypt/dnscrypt-resolvers#959]
The list only contains one dnsforge DNS resolver (unfortunately the "hard" one).
Please add also the DoH stamps for:

https://dnsforge.de/dns-query
https://clean.dnsforge.de/dns-query
https://hard.dnsforge.de/dns-query

**Comment by jedisct1** [comment]
See https://github.com/DNSCrypt/dnscrypt-resolvers/blob/master/CONTRIBUTING.md
